# Columns Method

In [2]:
import pandas as pd
import numpy as np

In [22]:
emp = pd.DataFrame({
    "name": ["amit sharma", "SARA KHAN", "john dsouza", "priya rao", "ravi kumar"],
    "dept": ["IT", "HR", "IT", "SALES", "hr"],
    "salary": [50000, 40000, 95000, 38000, 45000],
    "joining_date": ["2020-01-15", "2019-06-01", "2015-03-20", "2023-11-05", "2021-08-30"],
})

In [23]:
# 1. Clean `name` (title case) and `dept` (upper case).
emp["name"] = emp["name"].str.strip().str.title()
emp["dept"] = emp["dept"].str.upper()
emp

          name   dept  salary joining_date
0  Amit Sharma     IT   50000   2020-01-15
1    Sara Khan     HR   40000   2019-06-01
2  John Dsouza     IT   95000   2015-03-20
3    Priya Rao  SALES   38000   2023-11-05
4   Ravi Kumar     HR   45000   2021-08-30

In [24]:
# 2. Split `name` into `first_name` and `last_name`.
emp[["first_Name","Last_Name"]] = emp["name"].str.split(" ",expand=True)
emp.head()

          name   dept  salary joining_date first_Name Last_Name
0  Amit Sharma     IT   50000   2020-01-15       Amit    Sharma
1    Sara Khan     HR   40000   2019-06-01       Sara      Khan
2  John Dsouza     IT   95000   2015-03-20       John    Dsouza
3    Priya Rao  SALES   38000   2023-11-05      Priya       Rao
4   Ravi Kumar     HR   45000   2021-08-30       Ravi     Kumar

In [25]:
# 3. Add `annual_salary` (salary * 12) and `tax` (10% of annual salary).
emp["annual_salary"] = emp["salary"] * 12
emp["tax"] = 10 * emp["annual_salary"]/100

In [26]:
emp

,name,dept,salary,joining_date,first_Name,Last_Name,annual_salary,tax
0,Amit Sharma,IT,50000,2020-01-15,Amit,Sharma,600000,60000.0
1,Sara Khan,HR,40000,2019-06-01,Sara,Khan,480000,48000.0
2,John Dsouza,IT,95000,2015-03-20,John,Dsouza,1140000,114000.0
3,Priya Rao,SALES,38000,2023-11-05,Priya,Rao,456000,45600.0
4,Ravi Kumar,HR,45000,2021-08-30,Ravi,Kumar,540000,54000.0

In [28]:
# 4. Add a column `level`: above 90000 = "Senior", above 45000 = "Mid", else "Junior".


emp["level"] = np.select([emp["salary"] > 90000,emp["salary"] > 45000],["Senior","Mid"],default="Junior")

In [29]:
emp

,name,dept,salary,joining_date,first_Name,Last_Name,annual_salary,tax,level
0,Amit Sharma,IT,50000,2020-01-15,Amit,Sharma,600000,60000.0,Mid
1,Sara Khan,HR,40000,2019-06-01,Sara,Khan,480000,48000.0,Junior
2,John Dsouza,IT,95000,2015-03-20,John,Dsouza,1140000,114000.0,Senior
3,Priya Rao,SALES,38000,2023-11-05,Priya,Rao,456000,45600.0,Junior
4,Ravi Kumar,HR,45000,2021-08-30,Ravi,Kumar,540000,54000.0,Junior

In [30]:
# 5. Map the department to a head: IT -> "Mr. Rao", HR -> "Ms. Iyer", SALES -> "Mr. Shah".
dept_head = {"IT":"Mr. Rao", "HR":"Ms. Iyer", "SALES":"Mr. Shah"}
emp["dept_head"] = emp["dept"].map(dept_head)

In [31]:
emp

,name,dept,salary,joining_date,first_Name,Last_Name,annual_salary,tax,level,dept_head
0,Amit Sharma,IT,50000,2020-01-15,Amit,Sharma,600000,60000.0,Mid,Mr. Rao
1,Sara Khan,HR,40000,2019-06-01,Sara,Khan,480000,48000.0,Junior,Ms. Iyer
2,John Dsouza,IT,95000,2015-03-20,John,Dsouza,1140000,114000.0,Senior,Mr. Rao
3,Priya Rao,SALES,38000,2023-11-05,Priya,Rao,456000,45600.0,Junior,Mr. Shah
4,Ravi Kumar,HR,45000,2021-08-30,Ravi,Kumar,540000,54000.0,Junior,Ms. Iyer

In [35]:
# 6. Convert `joining_date` to a date and add `joining_year` and `joining_month_name`.
emp["joining_date"] = pd.to_datetime(emp["joining_date"])
emp["joining_year"] = emp["joining_date"].dt.year
emp["joining_month_name"] = emp["joining_date"].dt.month_name()
emp[["name", "joining_date", "joining_year", "joining_month_name"]]

          name joining_date  joining_year joining_month_name
0  Amit Sharma   2020-01-15          2020            January
1    Sara Khan   2019-06-01          2019               June
2  John Dsouza   2015-03-20          2015              March
3    Priya Rao   2023-11-05          2023           November
4   Ravi Kumar   2021-08-30          2021             August

In [37]:
# 7. Add `years_worked` = whole years between joining date and 2026-09-23.
emp["years_worked"] = ((pd.Timestamp("2026-09-23") - emp["joining_date"]).dt.days / 365).astype(int)

In [39]:
emp[["name", "joining_date", "joining_year", "joining_month_name", "years_worked"]]

          name joining_date  joining_year joining_month_name  years_worked
0  Amit Sharma   2020-01-15          2020            January             6
1    Sara Khan   2019-06-01          2019               June             7
2  John Dsouza   2015-03-20          2015              March            11
3    Priya Rao   2023-11-05          2023           November             2
4   Ravi Kumar   2021-08-30          2021             August             5

In [40]:
# 8. Add a salary band using `pd.cut`: 0-40000 "Low", 40000-70000 "Medium", 70000+ "High".
pd.cut(emp["salary"], bins=[0,40000,70000,1000000],labels=["Low","Mwdium","High"])

0    Mwdium
1       Low
2      High
3       Low
4    Mwdium
Name: salary, dtype: category
Categories (3, str): ['Low' < 'Mwdium' < 'High']

In [41]:
emp

,name,dept,salary,joining_date,first_Name,Last_Name,annual_salary,tax,level,dept_head,joining_year,joining_month_name,years_worked
0,Amit Sharma,IT,50000,2020-01-15,Amit,Sharma,600000,60000.0,Mid,Mr. Rao,2020,January,6
1,Sara Khan,HR,40000,2019-06-01,Sara,Khan,480000,48000.0,Junior,Ms. Iyer,2019,June,7
2,John Dsouza,IT,95000,2015-03-20,John,Dsouza,1140000,114000.0,Senior,Mr. Rao,2015,March,11
3,Priya Rao,SALES,38000,2023-11-05,Priya,Rao,456000,45600.0,Junior,Mr. Shah,2023,November,2
4,Ravi Kumar,HR,45000,2021-08-30,Ravi,Kumar,540000,54000.0,Junior,Ms. Iyer,2021,August,5