SECTION B – PYTHON – 25 QUESTIONS

45. 
46. Identify None values in a list.
47. Create a dictionary with CustomerID as key and CustomerName as value.
48. Create a function that classifies an order as High when value is 50000 or more.
49. Calculate average employee salary using Python.
50. Find employees whose salary is above the average.
51. Using Pandas, create a DataFrame from customer records.
52. Using Pandas, filter Premium customers.
53. Using Pandas, replace missing City with Unknown.
54. Using Pandas, calculate OrderValue as Quantity multiplied by UnitPrice.
55. Using Pandas, calculate total order value by CustomerID.
56. Using Pandas, calculate average UnitPrice by Product Category.
57. Using Pandas, find customers with more than one order.
58. Using Pandas, sort employees by Salary descending.
59. Using Pandas, find the second-highest distinct salary.
60. Using Pandas, merge Customers and Orders using CustomerID.
61. Using Pandas, left join Customers and Orders and identify customers without orders.
62. Read a CSV file and handle missing values.
63. Check whether a dataset contains duplicate records.
64. Explain the difference between list, tuple, set and dictionary with examples.
65. Write a reusable function that validates required DataFrame columns.

In [2]:
import pandas as pd

In [ ]:
INSERT INTO dbo.Orders
(
    ,
    CustomerID,
    ProductID,
    OrderDate,
    Quantity,
    UnitPrice,
    OrderStatus
)
VALUES
(5001, 201, 301, '2025-01-05', 1, 75000, 'Completed'),
(5002, 201, 303, '2025-01-18', 2,  3000, 'Completed'),
(5003, 202, 302, '2025-02-10', 2, 25000, 'Completed'),
(5004, 203, 304, '2025-02-15', 3,  1500, 'Cancelled'),
(5005, 203, 305, '2025-03-01', 2, 12000, 'Completed'),
(5006, 204, 306, '2025-03-12', 4,  8000, 'Completed'),
(5007, 205, 301, '2025-04-07', 1, 75000, 'Completed'),
(5008, 206, 302, '2025-04-19', 1, 25000, 'Pending'),
(5009, 207, 303, '2025-05-08', 5,  3000, 'Completed'),
(5010, 201, 302, '2025-05-20', 1, 25000, 'Completed'),
(5011, 202, 306, '2025-06-03', 2,  8000, 'Completed'),
(5012, 205, 304, '2025-06-18', 2,  1500, 'Completed');

In [4]:
df = pd.DataFrame({
"OrderID":[ 5001,5002,5003,5004,5005,5006,5007,5008,5009,5010,5011,5012],
"CustomerID":[201,201,202,203,203,204,205,206,207,201,202,205],
"ProductID":[301,303,302,304,305,306,301,302,303,302,306,304],
"OrderDate":['2025-01-05','2025-01-18','2025-02-10','2025-02-15','2025-03-01','2025-03-12','2025-04-07','2025-04-19',
'2025-05-08','2025-05-20','2025-06-03','2025-06-18'],
"Quantity":[1,2,2,3,2,4,1,1,5,1,2,2],
"UnitPrice":[75000,3000,25000,1500,12000,8000,75000,25000,3000,25000,8000,1500],
"OrderStatus":['Completed','Completed','Completed','Completed','Completed','Completed','Completed','Pending','Completed','Completed'
,'Completed','Completed']

})

In [5]:
df

,OrderID,CustomerID,ProductID,OrderDate,Quantity,UnitPrice,OrderStatus
0,5001,201,301,2025-01-05,1,75000,Completed
1,5002,201,303,2025-01-18,2,3000,Completed
2,5003,202,302,2025-02-10,2,25000,Completed
3,5004,203,304,2025-02-15,3,1500,Completed
4,5005,203,305,2025-03-01,2,12000,Completed
5,5006,204,306,2025-03-12,4,8000,Completed
6,5007,205,301,2025-04-07,1,75000,Completed
7,5008,206,302,2025-04-19,1,25000,Pending
8,5009,207,303,2025-05-08,5,3000,Completed
9,5010,201,302,2025-05-20,1,25000,Completed
10,5011,202,306,2025-06-03,2,8000,Completed
11,5012,205,304,2025-06-18,2,1500,Completed

In [14]:
df.dtypes

OrderID        int64
CustomerID     int64
ProductID      int64
OrderDate        str
Quantity       int64
UnitPrice      int64
OrderStatus      str
dtype: object

In [21]:
# Create a list of completed order values from the Orders dataset.

CompletedOrders = [ d['Quantity']*d['UnitPrice'] for _,d in df.iterrows() if d['OrderStatus'] == 'Completed']
CompletedOrders

[75000, 6000, 50000, 4500, 24000, 32000, 75000, 15000, 25000, 16000, 3000]

In [27]:
#we can get this using loc as well
compOrd = df.loc[df["OrderStatus"] == "Completed", "Quantity"]*df.loc[df["OrderStatus"] == "Completed", "UnitPrice"]
COList = compOrd.tolist()
COList

[75000, 6000, 50000, 4500, 24000, 32000, 75000, 15000, 25000, 16000, 3000]

In [8]:
df[df["OrderStatus"]=="Completed"]

,OrderID,CustomerID,ProductID,OrderDate,Quantity,UnitPrice,OrderStatus
0,5001,201,301,2025-01-05,1,75000,Completed
1,5002,201,303,2025-01-18,2,3000,Completed
2,5003,202,302,2025-02-10,2,25000,Completed
3,5004,203,304,2025-02-15,3,1500,Completed
4,5005,203,305,2025-03-01,2,12000,Completed
5,5006,204,306,2025-03-12,4,8000,Completed
6,5007,205,301,2025-04-07,1,75000,Completed
8,5009,207,303,2025-05-08,5,3000,Completed
9,5010,201,302,2025-05-20,1,25000,Completed
10,5011,202,306,2025-06-03,2,8000,Completed
11,5012,205,304,2025-06-18,2,1500,Completed

In [35]:
# Write a function that returns the total of a list of numbers.
def Tootall(COList):
    total =0
    for i in COList:
        total += i
    return total

def Tootal(COList):
    return "The sum of list is ",sum(COList)

In [36]:
Tootal(COList)

('The sum of list is ', 325500)

In [40]:
# Find highest, lowest and average order value from a list.
print("THe Highest value from the list is", max(COList))
print("THe Lowest value from the list is", min(COList))
print("THe Average value from the list is", sum(COList)/len(COList))

THe Highest value from the list is 75000
THe Lowest value from the list is 3000
THe Average value from the list is 29590.909090909092

In [49]:
cust_iddff = df["CustomerID"]
c_idsc = cust_iddff.tolist()

In [50]:
# Count occurrences of each customer ID using a dictionary.
# CustomerID = df.loc[df["CustomerID"]]
# c_ids = CustomerID.tolist()
counts = {}
for cust_id in c_idsc:
    counts[cust_id] = counts.get(cust_id,0)+1
counts

{201: 3, 202: 2, 203: 2, 204: 1, 205: 2, 206: 1, 207: 1}

In [51]:
dff

0     201
1     201
2     202
3     203
4     203
5     204
6     205
7     206
8     207
9     201
10    202
11    205
Name: CustomerID, dtype: int64

In [47]:
# Remove duplicate customer names while preserving order.
dff = df["CustomerName"]
c_names = dff.tolist()

KeyError: 'CustomerName'