# Data Cleaning

In [1]:
import pandas as pd

In [25]:
students = pd.DataFrame({
    " Roll No ": [1, 2, 3, 4, 4, 5],
    "Student Name": [" amit", "SARA ", "john", "priya", "priya", None],
    "City": ["pune", "PUNE", "delhi", None, None, "Mumbai"],
    "Marks": ["85", "92", "abc", "65", "65", "70"],
    "Joined": ["2026-01-05", "2026-01-06", "07-01-2026", "2026-01-08", "2026-01-08", None],
})

In [26]:
# 1. Print how many missing values each column has.
print("Number of null value in each col")
students.isna().sum()

Number of null value in each col

 Roll No        0
Student Name    1
City            2
Marks           0
Joined          1
dtype: int64

In [27]:
# 2. Remove the duplicate row.
print("Before drop duplicate :", len(students))
stu = students.drop_duplicates(subset=[" Roll No "],keep=False) #both remove
print("After drop duplicate :", len(stu))

Before drop duplicate : 6
After drop duplicate : 4

In [28]:
# 3. Clean the column names (no spaces, small letters, underscore).
students.columns = students.columns.str.strip().str.lower().str.replace(" ","_")
print(list(students.columns))
print(students.head())

['roll_no', 'student_name', 'city', 'marks', 'joined']
   roll_no student_name   city marks      joined
0        1         amit   pune    85  2026-01-05
1        2        SARA    PUNE    92  2026-01-06
2        3         john  delhi   abc  07-01-2026
3        4        priya    NaN    65  2026-01-08
4        4        priya    NaN    65  2026-01-08

In [33]:
# 4. Clean the student names and cities (no extra spaces, title case).
students["student_name"] = students["student_name"].str.strip().str.title()
print(students[["student_name","city"]])

  student_name    city
0         Amit    pune
1         Sara    PUNE
2         John   delhi
3        Priya     NaN
4        Priya     NaN
5          NaN  Mumbai

In [39]:
# 5. Convert `marks` to a number (bad values become missing), then fill the missing marks
#    with the average.
students["marks"] = pd.to_numeric(students["marks"],errors="coerce")
students["marks"] = students["marks"].fillna(students["marks"].mean())
students["marks"]

0    85.0
1    92.0
2    75.4
3    65.0
4    65.0
5    70.0
Name: marks, dtype: float64

In [48]:
# 6. Convert `joined` to a date.
students = students.rename(columns = {"joined":"date"})
students.columns
students["date"] = pd.to_datetime(students["date"],errors="coerce",format="mixed",dayfirst=True)
students.head()

   roll_no student_name   city  marks       date
0        1         Amit   pune   85.0 2026-05-01
1        2         Sara   PUNE   92.0 2026-06-01
2        3         John  delhi   75.4 2026-01-07
3        4        Priya    NaN   65.0 2026-08-01
4        4        Priya    NaN   65.0 2026-08-01

In [49]:
# 7. Fill the missing city with `"Unknown"`.
students["city"] = students["city"].fillna("unknown")
students["city"]

0       pune
1       PUNE
2      delhi
3    unknown
4    unknown
5     Mumbai
Name: city, dtype: str

In [50]:
# 8. Print the final table and `info()`.
print(students.head())
students.info()

   roll_no student_name     city  marks       date
0        1         Amit     pune   85.0 2026-05-01
1        2         Sara     PUNE   92.0 2026-06-01
2        3         John    delhi   75.4 2026-01-07
3        4        Priya  unknown   65.0 2026-08-01
4        4        Priya  unknown   65.0 2026-08-01
<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   roll_no       6 non-null      int64
 1   student_name  5 non-null      str
 2   city          6 non-null      str
 3   marks         6 non-null      float64
 4   date          5 non-null      datetime64[us]
dtypes: datetime64[us](1), float64(1), int64(1), str(2)
memory usage: 372.0 bytes

In [51]:
students

   roll_no student_name     city  marks       date
0        1         Amit     pune   85.0 2026-05-01
1        2         Sara     PUNE   92.0 2026-06-01
2        3         John    delhi   75.4 2026-01-07
3        4        Priya  unknown   65.0 2026-08-01
4        4        Priya  unknown   65.0 2026-08-01
5        5          NaN   Mumbai   70.0        NaT

In [55]:
students["student_name"] = students["student_name"].fillna("unknown")
students["date"] = students["date"].fillna("Not available")

In [56]:
students

   roll_no student_name     city  marks                 date
0        1         Amit     pune   85.0  2026-05-01 00:00:00
1        2         Sara     PUNE   92.0  2026-06-01 00:00:00
2        3         John    delhi   75.4  2026-01-07 00:00:00
3        4        Priya  unknown   65.0  2026-08-01 00:00:00
4        4        Priya  unknown   65.0  2026-08-01 00:00:00
5        5      unknown   Mumbai   70.0        Not available