# Merge and Concat

In [3]:
import pandas as pd

In [4]:
emp = pd.DataFrame({
    "emp_id": [1, 2, 3, 4],
    "name": ["Amit", "Sara", "John", "Priya"],
    "dept_id": [10, 20, 10, 99],
})
dept = pd.DataFrame({
    "dept_id": [10, 20, 30],
    "dept_name": ["IT", "HR", "Finance"],
})
salary = pd.DataFrame({
    "emp_id": [1, 2, 3, 4],
    "salary": [50000, 40000, 65000, 38000],
})

In [6]:
# 1. Inner join `emp` and `dept`. How many rows do you get and who is missing?
join = emp.merge(dept, on="dept_id",how="inner")
print(f"rows : {len(join)} of{len(emp)}")
join

rows : 3 of4

   emp_id  name  dept_id dept_name
0       1  Amit       10        IT
1       2  Sara       20        HR
2       3  John       10        IT

In [8]:
# 2. Left join instead, so nobody is lost.
left = emp.merge(dept, on="dept_id", how="left")
left

   emp_id   name  dept_id dept_name
0       1   Amit       10        IT
1       2   Sara       20        HR
2       3   John       10        IT
3       4  Priya       99       NaN

In [9]:
# 3. Join all three tables and show name, dept_name, salary.
join3 = emp.merge(dept, on="dept_id", how="left").merge(salary, on="emp_id", how="left")
join3[["name", "dept_name", "salary"]]

    name dept_name  salary
0   Amit        IT   50000
1   Sara        HR   40000
2   John        IT   65000
3  Priya       NaN   38000

In [20]:
# 4. Find employees whose `dept_id` does not exist in `dept` (use `indicator`).
check = emp.merge(dept, on="dept_id",how="outer" ,indicator=True )
print(check)
print()
print("Emp with wrong dept_id:")
print(check[check["_merge"] == "left_only"][["name","dept_id"]])

   emp_id   name  dept_id dept_name      _merge
0     1.0   Amit       10        IT        both
1     3.0   John       10        IT        both
2     2.0   Sara       20        HR        both
3     NaN    NaN       30   Finance  right_only
4     4.0  Priya       99       NaN   left_only

Emp with wrong dept_id:
    name  dept_id
4  Priya       99

In [24]:
# 5. Find departments that have no employee.
# dcheck = emp.merge(dept, on="dept_id", how="outer", indicator=True)
print("Dept which have no emp")
check[check["_merge"] == "right_only"]

Dept which have no emp

   emp_id name  dept_id dept_name      _merge
3     NaN  NaN       30   Finance  right_only

In [37]:
# 6. Stack `emp` with a new row for employee 5 (`Ravi`, dept 20) using `concat`.
# new_emp = pd.DataFrame({"emp_id":[5],"name":["Ravi"], "dept_id" :[20]})
new_emp = pd.DataFrame({"emp_id": [5], "name": ["Ravi"], "dept_id": [20]})
emp_all = pd.concat([emp, new_emp], ignore_index=True)
emp_all

   emp_id   name  dept_id
0       1   Amit       10
1       2   Sara       20
2       3   John       10
3       4  Priya       99
4       5   Ravi       20

In [35]:
# 7. Total salary per department name.
(emp.merge(dept,on="dept_id",how="inner").merge(salary,on="emp_id",how="inner").groupby("dept_name")["salary"].sum())

dept_name
HR     40000
IT    115000
Name: salary, dtype: int64