In [2]:
import pandas as pd
import numpy as np

In [3]:
dict1 = {
    "name":['shweta' , 'snehal' , 'krishna' , 'asmi']  ,
    "marks":[45,78,94,78],
    "city":['rajura','rampur','wirur','vedabai']
}

In [4]:
df = pd.DataFrame(dict1)

In [5]:
df

      name  marks     city
0   shweta     45   rajura
1   snehal     78   rampur
2  krishna     94    wirur
3     asmi     78  vedabai

In [6]:

#exporting dataframe to csv
df.to_csv('friends.csv')

In [7]:
df.to_csv('friends_index.csv',index=False)

In [8]:
df

      name  marks     city
0   shweta     45   rajura
1   snehal     78   rampur
2  krishna     94    wirur
3     asmi     78  vedabai

In [9]:
df.head(2)

     name  marks    city
0  shweta     45  rajura
1  snehal     78  rampur

In [10]:
df.tail(2)

      name  marks     city
2  krishna     94    wirur
3     asmi     78  vedabai

In [11]:
df.describe()

          marks
count   4.00000
mean   73.75000
std    20.59733
min    45.00000
25%    69.75000
50%    78.00000
75%    82.00000
max    94.00000

In [12]:
#read existing excel i.e csv
sh = pd.read_csv('shwe.csv')

In [13]:
sh

   Unnamed: 0     name  marks     city
0           0   shweta     45   rajura
1           1   snehal     78   rampur
2           2  krishna     94    wirur
3           3     asmi     78  vedabai

In [14]:
sh['marks']

0    45
1    78
2    94
3    78
Name: marks, dtype: int64

In [15]:
sh['marks'][1]

np.int64(78)

In [16]:
sh['marks'][1]=50

C:\Users\hp\AppData\Local\Temp\ipykernel_16552\1850009520.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sh['marks'][1]=50

In [17]:
sh

   Unnamed: 0     name  marks     city
0           0   shweta     45   rajura
1           1   snehal     50   rampur
2           2  krishna     94    wirur
3           3     asmi     78  vedabai

In [18]:
sh.to_csv('shw.csv')

In [19]:
sh.index=['fir','sec','thir','forth']

In [20]:
sh

       Unnamed: 0     name  marks     city
fir             0   shweta     45   rajura
sec             1   snehal     50   rampur
thir            2  krishna     94    wirur
forth           3     asmi     78  vedabai

In [21]:
ser = pd.Series(np.random.rand(25))

In [22]:


ser

0     0.464292
1     0.551291
2     0.210518
3     0.941997
4     0.429382
5     0.254347
6     0.445245
7     0.312954
8     0.826624
9     0.259303
10    0.090889
11    0.209425
12    0.200072
13    0.725013
14    0.523881
15    0.132318
16    0.885928
17    0.514934
18    0.985372
19    0.871541
20    0.421725
21    0.721978
22    0.837883
23    0.007173
24    0.684118
dtype: float64

In [23]:
type(ser)

pandas.core.series.Series

In [26]:
#dataframe of random values
newdf = pd.DataFrame(np.random.rand(334,5), index = np.arange(334))

In [27]:
newdf

            0         1         2         3         4
0    0.510454  0.665881  0.505267  0.164880  0.918912
1    0.287946  0.909516  0.318583  0.099083  0.727648
2    0.471528  0.711164  0.795647  0.018825  0.103503
3    0.314163  0.163395  0.522674  0.241157  0.949979
4    0.650845  0.706756  0.213393  0.214318  0.811523
..        ...       ...       ...       ...       ...
329  0.814136  0.512117  0.320740  0.094268  0.036661
330  0.139177  0.239863  0.584919  0.295782  0.716680
331  0.243306  0.437178  0.795725  0.713145  0.942050
332  0.766904  0.223151  0.477857  0.422703  0.133342
333  0.798029  0.523018  0.068261  0.508832  0.397086

[334 rows x 5 columns]

In [27]:
newdf.head()

          0         1         2         3         4
0  0.975475  0.103299  0.634512  0.444079  0.145551
1  0.286215  0.009159  0.388518  0.718811  0.589597
2  0.138144  0.244921  0.657629  0.890246  0.896831
3  0.709872  0.542967  0.363693  0.413653  0.378789
4  0.794902  0.070005  0.688122  0.895167  0.775699

In [28]:
newdf.shape

(334, 5)

In [28]:
type(newdf)

pandas.core.frame.DataFrame

In [29]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.485941    0.474844    0.525247    0.472467    0.496706
std      0.281221    0.286078    0.287779    0.289798    0.297060
min      0.007776    0.002543    0.003047    0.001908    0.001036
25%      0.245170    0.223489    0.278751    0.222735    0.242199
50%      0.486020    0.484819    0.536667    0.432131    0.520224
75%      0.709533    0.725651    0.779119    0.717229    0.743302
max      0.975475    0.999783    0.999774    0.995742    0.998770

In [30]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [31]:
newdf[0][0] = "Asmi"

C:\Users\hp\AppData\Local\Temp\ipykernel_15780\214574092.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf[0][0] = "Asmi"
C:\Users\hp\AppData\Local\Temp\ipykernel_15780\214574092.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Asmi' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf[0][0] = "Asmi"

In [32]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [33]:
newdf.head()

          0         1         2         3         4
0      Asmi  0.103299  0.634512  0.444079  0.145551
1  0.286215  0.009159  0.388518  0.718811  0.589597
2  0.138144  0.244921  0.657629  0.890246  0.896831
3  0.709872  0.542967  0.363693  0.413653  0.378789
4  0.794902  0.070005  0.688122  0.895167  0.775699

In [34]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [35]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [36]:
newdf.to_numpy()

array([['Asmi', 0.10329864645467157, 0.6345123717764797,
        0.4440792310402609, 0.1455505241617353],
       [0.2862152417917392, 0.00915921140929954, 0.3885183369189491,
        0.7188112967014335, 0.5895965258798684],
       [0.13814437995332185, 0.24492110484314655, 0.6576293028919487,
        0.8902461479284017, 0.8968309407759135],
       ...,
       [0.43699709924970476, 0.7097353684813172, 0.845525764403387,
        0.35490584540099634, 0.8156324206112735],
       [0.9138544163007174, 0.8257389362159783, 0.8951442424169395,
        0.9693027221079826, 0.5588233159361938],
       [0.552295751522693, 0.29698838286962936, 0.7865044288241365,
        0.421136693097101, 0.9800200499436182]],
      shape=(334, 5), dtype=object)

In [37]:
newdf[0][0] =0.56

In [38]:
newdf.head()

          0         1         2         3         4
0      0.56  0.103299  0.634512  0.444079  0.145551
1  0.286215  0.009159  0.388518  0.718811  0.589597
2  0.138144  0.244921  0.657629  0.890246  0.896831
3  0.709872  0.542967  0.363693  0.413653  0.378789
4  0.794902  0.070005  0.688122  0.895167  0.775699

In [39]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [40]:
newdf.to_numpy()

array([[0.56, 0.10329864645467157, 0.6345123717764797,
        0.4440792310402609, 0.1455505241617353],
       [0.2862152417917392, 0.00915921140929954, 0.3885183369189491,
        0.7188112967014335, 0.5895965258798684],
       [0.13814437995332185, 0.24492110484314655, 0.6576293028919487,
        0.8902461479284017, 0.8968309407759135],
       ...,
       [0.43699709924970476, 0.7097353684813172, 0.845525764403387,
        0.35490584540099634, 0.8156324206112735],
       [0.9138544163007174, 0.8257389362159783, 0.8951442424169395,
        0.9693027221079826, 0.5588233159361938],
       [0.552295751522693, 0.29698838286962936, 0.7865044288241365,
        0.421136693097101, 0.9800200499436182]],
      shape=(334, 5), dtype=object)

In [41]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.56,0.286215,0.138144,0.709872,0.794902,0.084013,0.694285,0.563213,0.801625,0.108351,...,0.404996,0.756226,0.463411,0.943726,0.750135,0.693975,0.853426,0.436997,0.913854,0.552296
1,0.103299,0.009159,0.244921,0.542967,0.070005,0.785528,0.343494,0.290193,0.441809,0.372518,...,0.10354,0.211943,0.514499,0.481041,0.902786,0.291592,0.266787,0.709735,0.825739,0.296988
2,0.634512,0.388518,0.657629,0.363693,0.688122,0.19313,0.326697,0.09677,0.471117,0.46577,...,0.907574,0.895162,0.140023,0.651648,0.860634,0.640717,0.099612,0.845526,0.895144,0.786504
3,0.444079,0.718811,0.890246,0.413653,0.895167,0.141927,0.935216,0.537184,0.065306,0.987094,...,0.249508,0.471612,0.130633,0.345783,0.102023,0.223871,0.380435,0.354906,0.969303,0.421137
4,0.145551,0.589597,0.896831,0.378789,0.775699,0.573119,0.573238,0.574622,0.156335,0.925383,...,0.158242,0.052877,0.163027,0.535294,0.87586,0.887979,0.47504,0.815632,0.558823,0.98002

In [42]:
newdf.head()

          0         1         2         3         4
0      0.56  0.103299  0.634512  0.444079  0.145551
1  0.286215  0.009159  0.388518  0.718811  0.589597
2  0.138144  0.244921  0.657629  0.890246  0.896831
3  0.709872  0.542967  0.363693  0.413653  0.378789
4  0.794902  0.070005  0.688122  0.895167  0.775699

In [43]:
#sort rows in descending order
newdf.sort_index(axis=0, ascending=False)

            0         1         2         3         4
333  0.552296  0.296988  0.786504  0.421137  0.980020
332  0.913854  0.825739  0.895144  0.969303  0.558823
331  0.436997  0.709735  0.845526  0.354906  0.815632
330  0.853426  0.266787  0.099612  0.380435  0.475040
329  0.693975  0.291592  0.640717  0.223871  0.887979
..        ...       ...       ...       ...       ...
4    0.794902  0.070005  0.688122  0.895167  0.775699
3    0.709872  0.542967  0.363693  0.413653  0.378789
2    0.138144  0.244921  0.657629  0.890246  0.896831
1    0.286215  0.009159  0.388518  0.718811  0.589597
0        0.56  0.103299  0.634512  0.444079  0.145551

[334 rows x 5 columns]

In [44]:
#sort column in descending order
newdf.sort_index(axis=1, ascending=False)

            4         3         2         1         0
0    0.145551  0.444079  0.634512  0.103299      0.56
1    0.589597  0.718811  0.388518  0.009159  0.286215
2    0.896831  0.890246  0.657629  0.244921  0.138144
3    0.378789  0.413653  0.363693  0.542967  0.709872
4    0.775699  0.895167  0.688122  0.070005  0.794902
..        ...       ...       ...       ...       ...
329  0.887979  0.223871  0.640717  0.291592  0.693975
330  0.475040  0.380435  0.099612  0.266787  0.853426
331  0.815632  0.354906  0.845526  0.709735  0.436997
332  0.558823  0.969303  0.895144  0.825739  0.913854
333  0.980020  0.421137  0.786504  0.296988  0.552296

[334 rows x 5 columns]

In [45]:
#sort column in ascending order i.e bydefault ascending value is True
newdf.sort_index(axis=1)

            0         1         2         3         4
0        0.56  0.103299  0.634512  0.444079  0.145551
1    0.286215  0.009159  0.388518  0.718811  0.589597
2    0.138144  0.244921  0.657629  0.890246  0.896831
3    0.709872  0.542967  0.363693  0.413653  0.378789
4    0.794902  0.070005  0.688122  0.895167  0.775699
..        ...       ...       ...       ...       ...
329  0.693975  0.291592  0.640717  0.223871  0.887979
330  0.853426  0.266787  0.099612  0.380435  0.475040
331  0.436997  0.709735  0.845526  0.354906  0.815632
332  0.913854  0.825739  0.895144  0.969303  0.558823
333  0.552296  0.296988  0.786504  0.421137  0.980020

[334 rows x 5 columns]

In [46]:
newdf.head()

          0         1         2         3         4
0      0.56  0.103299  0.634512  0.444079  0.145551
1  0.286215  0.009159  0.388518  0.718811  0.589597
2  0.138144  0.244921  0.657629  0.890246  0.896831
3  0.709872  0.542967  0.363693  0.413653  0.378789
4  0.794902  0.070005  0.688122  0.895167  0.775699

In [47]:
newdf[0]

0          0.56
1      0.286215
2      0.138144
3      0.709872
4      0.794902
         ...
329    0.693975
330    0.853426
331    0.436997
332    0.913854
333    0.552296
Name: 0, Length: 334, dtype: object

In [48]:
type(newdf[0])

pandas.core.series.Series

In [49]:
##view i.e when we change in new one then in orignal also change
newdf2 = newdf

In [50]:
newdf2[0][0] = 9875

C:\Users\hp\AppData\Local\Temp\ipykernel_15780\3412016840.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf2[0][0] = 9875

In [51]:
newdf

            0         1         2         3         4
0        9875  0.103299  0.634512  0.444079  0.145551
1    0.286215  0.009159  0.388518  0.718811  0.589597
2    0.138144  0.244921  0.657629  0.890246  0.896831
3    0.709872  0.542967  0.363693  0.413653  0.378789
4    0.794902  0.070005  0.688122  0.895167  0.775699
..        ...       ...       ...       ...       ...
329  0.693975  0.291592  0.640717  0.223871  0.887979
330  0.853426  0.266787  0.099612  0.380435  0.475040
331  0.436997  0.709735  0.845526  0.354906  0.815632
332  0.913854  0.825739  0.895144  0.969303  0.558823
333  0.552296  0.296988  0.786504  0.421137  0.980020

[334 rows x 5 columns]

In [52]:
# it is copy  newdf2 = newdf [:] or
newdf2 = newdf.copy()

In [53]:
newdf2[0][0] = 98759

C:\Users\hp\AppData\Local\Temp\ipykernel_15780\3212690909.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf2[0][0] = 98759
C:\Users\hp\AppData\Local\Temp\ipykernel_15780\3212690909.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf2[0][0] = 98759

In [54]:
#it is copy so no change
newdf

            0         1         2         3         4
0        9875  0.103299  0.634512  0.444079  0.145551
1    0.286215  0.009159  0.388518  0.718811  0.589597
2    0.138144  0.244921  0.657629  0.890246  0.896831
3    0.709872  0.542967  0.363693  0.413653  0.378789
4    0.794902  0.070005  0.688122  0.895167  0.775699
..        ...       ...       ...       ...       ...
329  0.693975  0.291592  0.640717  0.223871  0.887979
330  0.853426  0.266787  0.099612  0.380435  0.475040
331  0.436997  0.709735  0.845526  0.354906  0.815632
332  0.913854  0.825739  0.895144  0.969303  0.558823
333  0.552296  0.296988  0.786504  0.421137  0.980020

[334 rows x 5 columns]

In [55]:
newdf.loc[0,0] = 654

In [56]:
newdf.head(2)

          0         1         2         3         4
0       654  0.103299  0.634512  0.444079  0.145551
1  0.286215  0.009159  0.388518  0.718811  0.589597

In [57]:
newdf.columns = list("ABCDE")

In [58]:
newdf.head(2)

          A         B         C         D         E
0       654  0.103299  0.634512  0.444079  0.145551
1  0.286215  0.009159  0.388518  0.718811  0.589597

In [59]:
newdf.loc[0,0] = 654

In [60]:
#here 0 column insert 
newdf.head(2)

          A         B         C         D         E      0
0       654  0.103299  0.634512  0.444079  0.145551  654.0
1  0.286215  0.009159  0.388518  0.718811  0.589597    NaN

In [61]:
newdf.loc[0,'A'] = 65496

In [62]:
newdf.head()

          A         B         C         D         E      0
0     65496  0.103299  0.634512  0.444079  0.145551  654.0
1  0.286215  0.009159  0.388518  0.718811  0.589597    NaN
2  0.138144  0.244921  0.657629  0.890246  0.896831    NaN
3  0.709872  0.542967  0.363693  0.413653  0.378789    NaN
4  0.794902  0.070005  0.688122  0.895167  0.775699    NaN

In [63]:
newdf.drop(0)

            A         B         C         D         E   0
1    0.286215  0.009159  0.388518  0.718811  0.589597 NaN
2    0.138144  0.244921  0.657629  0.890246  0.896831 NaN
3    0.709872  0.542967  0.363693  0.413653  0.378789 NaN
4    0.794902  0.070005  0.688122  0.895167  0.775699 NaN
5    0.084013  0.785528  0.193130  0.141927  0.573119 NaN
..        ...       ...       ...       ...       ...  ..
329  0.693975  0.291592  0.640717  0.223871  0.887979 NaN
330  0.853426  0.266787  0.099612  0.380435  0.475040 NaN
331  0.436997  0.709735  0.845526  0.354906  0.815632 NaN
332  0.913854  0.825739  0.895144  0.969303  0.558823 NaN
333  0.552296  0.296988  0.786504  0.421137  0.980020 NaN

[333 rows x 6 columns]

In [64]:
#here o in row cancel
newdf.head()

          A         B         C         D         E      0
0     65496  0.103299  0.634512  0.444079  0.145551  654.0
1  0.286215  0.009159  0.388518  0.718811  0.589597    NaN
2  0.138144  0.244921  0.657629  0.890246  0.896831    NaN
3  0.709872  0.542967  0.363693  0.413653  0.378789    NaN
4  0.794902  0.070005  0.688122  0.895167  0.775699    NaN

In [65]:
#here column 0 cancel
newdf = newdf.drop(0, axis=1)

In [66]:
newdf.head()

          A         B         C         D         E
0     65496  0.103299  0.634512  0.444079  0.145551
1  0.286215  0.009159  0.388518  0.718811  0.589597
2  0.138144  0.244921  0.657629  0.890246  0.896831
3  0.709872  0.542967  0.363693  0.413653  0.378789
4  0.794902  0.070005  0.688122  0.895167  0.775699

In [67]:
newdf.loc[[1,2],['C','D']]

          C         D
1  0.388518  0.718811
2  0.657629  0.890246

In [68]:
newdf.head()

          A         B         C         D         E
0     65496  0.103299  0.634512  0.444079  0.145551
1  0.286215  0.009159  0.388518  0.718811  0.589597
2  0.138144  0.244921  0.657629  0.890246  0.896831
3  0.709872  0.542967  0.363693  0.413653  0.378789
4  0.794902  0.070005  0.688122  0.895167  0.775699

In [69]:
newdf.loc[:,['C','D']]

            C         D
0    0.634512  0.444079
1    0.388518  0.718811
2    0.657629  0.890246
3    0.363693  0.413653
4    0.688122  0.895167
..        ...       ...
329  0.640717  0.223871
330  0.099612  0.380435
331  0.845526  0.354906
332  0.895144  0.969303
333  0.786504  0.421137

[334 rows x 2 columns]

In [70]:
newdf.loc[[1,2],:]

          A         B         C         D         E
1  0.286215  0.009159  0.388518  0.718811  0.589597
2  0.138144  0.244921  0.657629  0.890246  0.896831

In [71]:
newdf.loc[newdf['A']<0.4]

            A         B         C         D         E
1    0.286215  0.009159  0.388518  0.718811  0.589597
2    0.138144  0.244921  0.657629  0.890246  0.896831
5    0.084013  0.785528  0.193130  0.141927  0.573119
9    0.108351  0.372518  0.465770  0.987094  0.925383
12   0.266217  0.099892  0.229186  0.834051  0.689398
..        ...       ...       ...       ...       ...
316  0.336118  0.863602  0.277486  0.632682  0.807520
320  0.381455  0.738517  0.654044  0.907154  0.290397
321  0.159757  0.397376  0.415312  0.875821  0.638827
322  0.301061  0.265078  0.169982  0.317486  0.483105
323  0.355839  0.607122  0.756928  0.224676  0.888604

[135 rows x 5 columns]

In [72]:
newdf.loc[(newdf['A']<0.4) & (newdf['C']>0.4)]

            A         B         C         D         E
2    0.138144  0.244921  0.657629  0.890246  0.896831
9    0.108351  0.372518  0.465770  0.987094  0.925383
15    0.26795  0.216770  0.627697  0.693043  0.300983
16   0.091281  0.261017  0.879562  0.233144  0.731771
26   0.148096  0.805748  0.633281  0.252145  0.761793
..        ...       ...       ...       ...       ...
308   0.10489  0.394565  0.637280  0.956952  0.722491
310   0.12681  0.338696  0.865049  0.332375  0.277540
320  0.381455  0.738517  0.654044  0.907154  0.290397
321  0.159757  0.397376  0.415312  0.875821  0.638827
323  0.355839  0.607122  0.756928  0.224676  0.888604

[86 rows x 5 columns]

In [73]:
newdf.head()

          A         B         C         D         E
0     65496  0.103299  0.634512  0.444079  0.145551
1  0.286215  0.009159  0.388518  0.718811  0.589597
2  0.138144  0.244921  0.657629  0.890246  0.896831
3  0.709872  0.542967  0.363693  0.413653  0.378789
4  0.794902  0.070005  0.688122  0.895167  0.775699

In [74]:
#if use rows and col name then use loc
#and if count then iloc 4 is a count
newdf.iloc[0,4]

np.float64(0.1455505241617353)

In [75]:
#[0,4] are rows and [1,3] are column
newdf.iloc[[0,4],[1,3]]

          B         D
0  0.103299  0.444079
4  0.070005  0.895167

In [76]:
newdf.drop([0])

            A         B         C         D         E
1    0.286215  0.009159  0.388518  0.718811  0.589597
2    0.138144  0.244921  0.657629  0.890246  0.896831
3    0.709872  0.542967  0.363693  0.413653  0.378789
4    0.794902  0.070005  0.688122  0.895167  0.775699
5    0.084013  0.785528  0.193130  0.141927  0.573119
..        ...       ...       ...       ...       ...
329  0.693975  0.291592  0.640717  0.223871  0.887979
330  0.853426  0.266787  0.099612  0.380435  0.475040
331  0.436997  0.709735  0.845526  0.354906  0.815632
332  0.913854  0.825739  0.895144  0.969303  0.558823
333  0.552296  0.296988  0.786504  0.421137  0.980020

[333 rows x 5 columns]

In [77]:
#only copy not orignally change
newdf.drop(['A','C'],axis=1)

            B         D         E
0    0.103299  0.444079  0.145551
1    0.009159  0.718811  0.589597
2    0.244921  0.890246  0.896831
3    0.542967  0.413653  0.378789
4    0.070005  0.895167  0.775699
..        ...       ...       ...
329  0.291592  0.223871  0.887979
330  0.266787  0.380435  0.475040
331  0.709735  0.354906  0.815632
332  0.825739  0.969303  0.558823
333  0.296988  0.421137  0.980020

[334 rows x 3 columns]

In [78]:
newdf.head()

          A         B         C         D         E
0     65496  0.103299  0.634512  0.444079  0.145551
1  0.286215  0.009159  0.388518  0.718811  0.589597
2  0.138144  0.244921  0.657629  0.890246  0.896831
3  0.709872  0.542967  0.363693  0.413653  0.378789
4  0.794902  0.070005  0.688122  0.895167  0.775699

In [79]:
#inplace=True means orignally change
newdf.drop(['A','D'], axis=1 , inplace = True)

In [80]:
newdf

            B         C         E
0    0.103299  0.634512  0.145551
1    0.009159  0.388518  0.589597
2    0.244921  0.657629  0.896831
3    0.542967  0.363693  0.378789
4    0.070005  0.688122  0.775699
..        ...       ...       ...
329  0.291592  0.640717  0.887979
330  0.266787  0.099612  0.475040
331  0.709735  0.845526  0.815632
332  0.825739  0.895144  0.558823
333  0.296988  0.786504  0.980020

[334 rows x 3 columns]

In [ ]:
newdf.drop([1,3], axis=0 , inplace = True) #inplace = Truemeans change in original without assign it another variable if inplace = Flase then not change in original DS

In [82]:
newdf

            B         C         E
0    0.103299  0.634512  0.145551
2    0.244921  0.657629  0.896831
4    0.070005  0.688122  0.775699
5    0.785528  0.193130  0.573119
6    0.343494  0.326697  0.573238
..        ...       ...       ...
329  0.291592  0.640717  0.887979
330  0.266787  0.099612  0.475040
331  0.709735  0.845526  0.815632
332  0.825739  0.895144  0.558823
333  0.296988  0.786504  0.980020

[332 rows x 3 columns]

In [83]:
#it start rows from 0 but add 1 more column index
newdf.reset_index()

     index         B         C         E
0        0  0.103299  0.634512  0.145551
1        2  0.244921  0.657629  0.896831
2        4  0.070005  0.688122  0.775699
3        5  0.785528  0.193130  0.573119
4        6  0.343494  0.326697  0.573238
..     ...       ...       ...       ...
327    329  0.291592  0.640717  0.887979
328    330  0.266787  0.099612  0.475040
329    331  0.709735  0.845526  0.815632
330    332  0.825739  0.895144  0.558823
331    333  0.296988  0.786504  0.980020

[332 rows x 4 columns]

In [84]:
#it not add i more column
newdf.reset_index(drop=True)

            B         C         E
0    0.103299  0.634512  0.145551
1    0.244921  0.657629  0.896831
2    0.070005  0.688122  0.775699
3    0.785528  0.193130  0.573119
4    0.343494  0.326697  0.573238
..        ...       ...       ...
327  0.291592  0.640717  0.887979
328  0.266787  0.099612  0.475040
329  0.709735  0.845526  0.815632
330  0.825739  0.895144  0.558823
331  0.296988  0.786504  0.980020

[332 rows x 3 columns]

In [85]:
  newdf['B'].isnull()

0      False
2      False
4      False
5      False
6      False
       ...
329    False
330    False
331    False
332    False
333    False
Name: B, Length: 332, dtype: bool

In [95]:
#newdf['B'] = None it is also used but it is not every time correct 
# None, 34,45  anything can be replace
newdf.loc[:,['B']]=None

In [96]:
newdf.head()

      B         C         E
0  None  0.634512  0.145551
2  None  0.657629  0.896831
4  None  0.688122  0.775699
5  None  0.193130  0.573119
6  None  0.326697  0.573238

In [94]:
newdf['B'].isnull()

0      False
2      False
4      False
5      False
6      False
       ...
329    False
330    False
331    False
332    False
333    False
Name: B, Length: 332, dtype: bool

In [97]:
newdf.loc[:,['B']]=56

In [98]:
newdf.head(5)

    B         C         E
0  56  0.634512  0.145551
2  56  0.657629  0.896831
4  56  0.688122  0.775699
5  56  0.193130  0.573119
6  56  0.326697  0.573238

In [99]:
newdf['B'].isnull()

0      False
2      False
4      False
5      False
6      False
       ...
329    False
330    False
331    False
332    False
333    False
Name: B, Length: 332, dtype: bool

In [101]:
df = pd.DataFrame({"name" : ['Alfread', 'Batman','catwoman'],
                   "toy" : [np.nan ,'Batmobile', 'Bullwhip'],
                   "born" : [pd.NaT, pd.Timestamp("1940-04-25"), pd.NaT]})

In [104]:
#drop rowwhich contain na
df.dropna()

     name        toy       born
1  Batman  Batmobile 1940-04-25

In [102]:
df.head()

       name        toy       born
0   Alfread        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  catwoman   Bullwhip        NaT

In [105]:
df.dropna(how = 'all')

       name        toy       born
0   Alfread        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  catwoman   Bullwhip        NaT

In [106]:
df = pd.DataFrame({"name" : ['Alfread', 'Batman','catwoman'],
                   "toy" : [np.nan ,np.nan , np.nan ],
                   "born" : [pd.NaT, pd.Timestamp("1940-04-25"), pd.NaT]})

In [107]:
df.head()

       name  toy       born
0   Alfread  NaN        NaT
1    Batman  NaN 1940-04-25
2  catwoman  NaN        NaT

In [109]:
df.dropna(how = 'all', axis=1)

       name       born
0   Alfread        NaT
1    Batman 1940-04-25
2  catwoman        NaT

In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.DataFrame({"name" : ['Alfread', 'Batman','Alfread'],
                   "toy" : [np.nan ,'Bullwhip' , np.nan ],
                   "born" : [pd.NaT, pd.Timestamp("1940-04-25"), pd.NaT]})

In [6]:
df

      name       toy       born
0  Alfread       NaN        NaT
1   Batman  Bullwhip 1940-04-25
2  Alfread       NaN        NaT

In [7]:
df.drop_duplicates(subset=['name'])

      name       toy       born
0  Alfread       NaN        NaT
1   Batman  Bullwhip 1940-04-25

In [8]:
#df.drop_duplicates(subset=['name'],keep=First)
#df.drop_duplicates(subset=['name'],keep=last)
df.drop_duplicates(subset=['name'],keep=False)

     name       toy       born
1  Batman  Bullwhip 1940-04-25

In [9]:
#numpy function
df.shape

(3, 3)

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str
 1   toy     1 non-null      str
 2   born    1 non-null      datetime64[us]
dtypes: datetime64[us](1), str(2)
memory usage: 204.0 bytes

In [11]:
#unique count
df['name'].value_counts(dropna=False)

name
Alfread    2
Batman     1
Name: count, dtype: int64

In [13]:
df['toy'].value_counts(dropna=False)

toy
NaN         2
Bullwhip    1
Name: count, dtype: int64

In [14]:
df['toy'].value_counts(dropna=True)

toy
Bullwhip    1
Name: count, dtype: int64

In [139]:
df.notnull()

   name    toy   born
0  True  False  False
1  True   True   True
2  True  False  False

In [140]:
df.isnull()

    name    toy   born
0  False   True   True
1  False  False  False
2  False   True   True