In [1]:
import pandas as pd

In [3]:
path = r"E:\Data Science\Pandas\customer_analytics_10000.csv"

In [4]:
df = pd.read_csv(path)

In [5]:
df

,Customer_ID,Age,Gender,City,Region,Income,Credit_Score,Account_Balance,Tenure_Months,Num_Transactions,...,Product_Type,Channel,Satisfaction_Score,Complaints,Last_Transaction_Date,Is_Active,Churn,Risk_Band,Marketing_Opt_In,Support_Tickets
0,C00001,23,Other,Hyderabad,South,40823.66,581.0,6084.29,80,12,...,Savings,Web,5.0,1,2025-04-10,True,0,Medium,False,2
1,C00002,62,Male,Delhi,Central,53091.08,805.0,28218.97,196,14,...,Investment,Phone,1.0,0,2024-07-05,True,0,Medium,True,0
2,C00003,55,Male,Delhi,Central,70984.02,421.0,12570.94,42,13,...,Credit Card,Branch,3.0,0,2024-02-09,True,0,Low,False,1
3,C00004,43,Male,Mumbai,South,51176.96,441.0,0.00,37,13,...,Personal Loan,Mobile App,3.0,1,2024-01-08,True,0,High,True,0
4,C00005,43,Unknown,Nagpur,North,58875.94,314.0,20451.36,213,27,...,Savings,Phone,4.0,1,2024-06-18,True,0,Low,True,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,C09996,45,Male,Pune,North,72308.96,NaN,30418.62,161,14,...,Mortgage,Web,5.0,0,2024-09-29,True,0,Medium,True,0
9996,C09997,75,Female,Nagpur,West,51327.02,300.0,29399.98,120,26,...,Savings,Phone,5.0,4,2025-03-11,True,0,High,True,1
9997,C09998,38,Male,Nagpur,South,48316.22,595.0,4564.80,114,11,...,Mortgage,Web,4.0,1,2024-10-09,True,0,Medium,True,1
9998,C09999,50,Unknown,Chennai,West,54334.05,845.0,41852.33,7,19,...,Savings,Mobile App,1.0,2,2024-10-15,True,1,High,True,3
9999,C10000,53,Male,Mumbai,West,81051.77,519.0,0.00,30,19,...,Investment,Branch,2.0,2,2025-05-16,True,0,Low,True,0

In [6]:
#df = pandas.read_csv(r"C:\python\CDS SH\Data Science\Pandas\customer_analytics_10000.csv")

# excel
#df = pd.read_excel(r".xlsx")

# parquet
#df = pd.read_parquet(r".parquet")

In [7]:
# tab seprated files
# df_tsv = pd.read_csv(path, sep="|")

# load only the columns given below:
- Customer_ID	Age	Gender

In [8]:
df_s = pd.read_csv(path, usecols=["Customer_ID","Age","Gender"])

In [9]:
df_s

     Customer_ID  Age   Gender
0         C00001   23    Other
1         C00002   62     Male
2         C00003   55     Male
3         C00004   43     Male
4         C00005   43  Unknown
...          ...  ...      ...
9995      C09996   45     Male
9996      C09997   75   Female
9997      C09998   38     Male
9998      C09999   50  Unknown
9999      C10000   53     Male

[10000 rows x 3 columns]

In [10]:
# pd.read_sql()
#pd.read_json()

In [13]:
# print first 5 rows
df.head()

,Customer_ID,Age,Gender,City,Region,Income,Credit_Score,Account_Balance,Tenure_Months,Num_Transactions,...,Product_Type,Channel,Satisfaction_Score,Complaints,Last_Transaction_Date,Is_Active,Churn,Risk_Band,Marketing_Opt_In,Support_Tickets
0,C00001,23,Other,Hyderabad,South,40823.66,581.0,6084.29,80,12,...,Savings,Web,5.0,1,2025-04-10,True,0,Medium,False,2
1,C00002,62,Male,Delhi,Central,53091.08,805.0,28218.97,196,14,...,Investment,Phone,1.0,0,2024-07-05,True,0,Medium,True,0
2,C00003,55,Male,Delhi,Central,70984.02,421.0,12570.94,42,13,...,Credit Card,Branch,3.0,0,2024-02-09,True,0,Low,False,1
3,C00004,43,Male,Mumbai,South,51176.96,441.0,0.00,37,13,...,Personal Loan,Mobile App,3.0,1,2024-01-08,True,0,High,True,0
4,C00005,43,Unknown,Nagpur,North,58875.94,314.0,20451.36,213,27,...,Savings,Phone,4.0,1,2024-06-18,True,0,Low,True,0

In [11]:
df.head(20)

,Customer_ID,Age,Gender,City,Region,Income,Credit_Score,Account_Balance,Tenure_Months,Num_Transactions,...,Product_Type,Channel,Satisfaction_Score,Complaints,Last_Transaction_Date,Is_Active,Churn,Risk_Band,Marketing_Opt_In,Support_Tickets
0,C00001,23,Other,Hyderabad,South,40823.66,581.0,6084.29,80,12,...,Savings,Web,5.0,1,2025-04-10,True,0,Medium,False,2
1,C00002,62,Male,Delhi,Central,53091.08,805.0,28218.97,196,14,...,Investment,Phone,1.0,0,2024-07-05,True,0,Medium,True,0
2,C00003,55,Male,Delhi,Central,70984.02,421.0,12570.94,42,13,...,Credit Card,Branch,3.0,0,2024-02-09,True,0,Low,False,1
3,C00004,43,Male,Mumbai,South,51176.96,441.0,0.00,37,13,...,Personal Loan,Mobile App,3.0,1,2024-01-08,True,0,High,True,0
4,C00005,43,Unknown,Nagpur,North,58875.94,314.0,20451.36,213,27,...,Savings,Phone,4.0,1,2024-06-18,True,0,Low,True,0
5,C00006,67,Male,Nagpur,West,74709.89,410.0,42149.01,218,15,...,Investment,Web,5.0,2,2025-07-07,True,0,Low,True,0
6,C00007,22,Female,Mumbai,South,57327.00,714.0,24551.21,162,12,...,Mortgage,Mobile App,4.0,3,2024-01-21,False,0,Low,True,0
7,C00008,58,Female,Bengaluru,South,69973.31,367.0,10035.10,81,12,...,Credit Card,Branch,3.0,0,2024-12-04,True,0,Medium,True,1
8,C00009,29,Male,Hyderabad,South,100040.03,459.0,41984.82,100,21,...,Savings,Mobile App,4.0,0,2024-05-15,True,0,High,True,2
9,C00010,23,Male,Nagpur,North,61219.11,806.0,17124.82,194,20,...,Investment,Phone,5.0,2,2024-01-04,True,0,Low,True,1
10,C00011,48,Male,Delhi,West,90945.43,692.0,20705.47,56,24,...,Personal Loan,Branch,2.0,0,2024-10-11,True,0,Low,True,2
11,C00012,74,Male,Bengaluru,South,77306.14,395.0,21359.40,126,22,...,Personal Loan,Phone,3.0,1,2025-11-24,True,0,Low,False,1
12,C00013,60,Male,Pune,Central,32720.68,811.0,42678.75,95,13,...,Mortgage,Web,3.0,1,2025-02-17,True,0,Low,True,2
13,C00014,62,Unknown,Chennai,West,40752.99,417.0,16924.87,43,17,...,Investment,Web,NaN,0,2024-03-11,True,0,Low,True,0
14,C00015,59,Male,Hyderabad,West,46660.89,810.0,10536.47,139,11,...,Savings,Phone,5.0,0,2024-04-17,True,0,Medium,False,0
15,C00016,63,Female,Hyderabad,West,46193.63,822.0,33678.37,166,18,...,Personal Loan,Mobile App,5.0,0,2025-10-16,False,0,Medium,True,1
16,C00017,47,Female,Delhi,Central,63013.63,578.0,41301.16,56,14,...,Personal Loan,Mobile App,5.0,0,2025-04-23,True,0,High,False,1
17,C00018,25,Male,Nagpur,West,78522.17,302.0,17184.30,161,14,...,Savings,Phone,3.0,0,2025-02-10,False,0,Low,True,0
18,C00019,66,Male,Nagpur,West,92613.49,812.0,12706.09,221,14,...,Savings,Phone,5.0,0,2024-04-11,True,0,Low,True,1
19,C00020,44,Female,Mumbai,North,71779.85,748.0,24434.85,218,15,...,Mortgage,Mobile App,4.0,2,2024-02-16,True,0,High,True,0

In [15]:
# see last 5 rows
df.tail()

,Customer_ID,Age,Gender,City,Region,Income,Credit_Score,Account_Balance,Tenure_Months,Num_Transactions,...,Product_Type,Channel,Satisfaction_Score,Complaints,Last_Transaction_Date,Is_Active,Churn,Risk_Band,Marketing_Opt_In,Support_Tickets
9995,C09996,45,Male,Pune,North,72308.96,NaN,30418.62,161,14,...,Mortgage,Web,5.0,0,2024-09-29,True,0,Medium,True,0
9996,C09997,75,Female,Nagpur,West,51327.02,300.0,29399.98,120,26,...,Savings,Phone,5.0,4,2025-03-11,True,0,High,True,1
9997,C09998,38,Male,Nagpur,South,48316.22,595.0,4564.80,114,11,...,Mortgage,Web,4.0,1,2024-10-09,True,0,Medium,True,1
9998,C09999,50,Unknown,Chennai,West,54334.05,845.0,41852.33,7,19,...,Savings,Mobile App,1.0,2,2024-10-15,True,1,High,True,3
9999,C10000,53,Male,Mumbai,West,81051.77,519.0,0.00,30,19,...,Investment,Branch,2.0,2,2025-05-16,True,0,Low,True,0

In [8]:
df.tail(10)

,Customer_ID,Age,Gender,City,Region,Income,Credit_Score,Account_Balance,Tenure_Months,Num_Transactions,...,Product_Type,Channel,Satisfaction_Score,Complaints,Last_Transaction_Date,Is_Active,Churn,Risk_Band,Marketing_Opt_In,Support_Tickets
9990,C09991,36,Other,Hyderabad,South,79661.65,814.0,12792.44,152,21,...,Personal Loan,Mobile App,5.0,0,2024-01-26,True,0,Medium,True,3
9991,C09992,30,Male,Nagpur,North,22998.98,705.0,0.00,50,16,...,Investment,Branch,4.0,0,2024-06-09,True,0,Medium,True,4
9992,C09993,71,Female,Delhi,West,83238.95,780.0,8986.71,96,17,...,Personal Loan,Phone,1.0,0,2024-08-26,True,0,High,True,2
9993,C09994,27,Male,Mumbai,Central,32955.19,395.0,3964.14,223,13,...,Credit Card,Mobile App,3.0,1,2025-04-13,True,0,Medium,False,2
9994,C09995,73,Male,Mumbai,Central,43344.72,775.0,0.00,16,28,...,Mortgage,Branch,4.0,0,2024-07-30,False,1,High,False,0
9995,C09996,45,Male,Pune,North,72308.96,NaN,30418.62,161,14,...,Mortgage,Web,5.0,0,2024-09-29,True,0,Medium,True,0
9996,C09997,75,Female,Nagpur,West,51327.02,300.0,29399.98,120,26,...,Savings,Phone,5.0,4,2025-03-11,True,0,High,True,1
9997,C09998,38,Male,Nagpur,South,48316.22,595.0,4564.80,114,11,...,Mortgage,Web,4.0,1,2024-10-09,True,0,Medium,True,1
9998,C09999,50,Unknown,Chennai,West,54334.05,845.0,41852.33,7,19,...,Savings,Mobile App,1.0,2,2024-10-15,True,1,High,True,3
9999,C10000,53,Male,Mumbai,West,81051.77,519.0,0.00,30,19,...,Investment,Branch,2.0,2,2025-05-16,True,0,Low,True,0

In [ ]:
df.sample(5, random_state=5)
# for random_state use any no. it just give same sample for same no. ex if 10 = 45,78,46,34,32 then it same for 10
#for 42 = 45,7,3,13,64 the run every time for 42 it give same output if random_state not set then it give sample roews diff each time

,Customer_ID,Age,Gender,City,Region,Income,Credit_Score,Account_Balance,Tenure_Months,Num_Transactions,...,Product_Type,Channel,Satisfaction_Score,Complaints,Last_Transaction_Date,Is_Active,Churn,Risk_Band,Marketing_Opt_In,Support_Tickets
7054,C07055,72,Female,Chennai,North,NaN,477.0,21511.44,212,15,...,Mortgage,Web,5.0,1,2025-08-18,True,0,Low,True,1
442,C00443,25,Female,Nagpur,North,31415.11,439.0,16988.53,218,21,...,Personal Loan,Web,3.0,0,2025-07-31,True,0,Low,True,1
3954,C03955,52,Male,Mumbai,West,96487.42,364.0,8900.46,110,20,...,Mortgage,Web,4.0,0,2024-10-20,True,0,Low,True,2
2288,C02289,72,Female,Chennai,West,68677.37,738.0,0.00,158,14,...,Mortgage,Web,5.0,2,2024-09-21,True,0,Low,True,4
3196,C03197,31,Female,Chennai,West,45890.55,632.0,46957.28,103,12,...,Credit Card,Branch,3.0,0,2024-01-12,True,0,High,False,1

In [12]:
df.shape 
# 1st is rows, # 2nd is columns

(10000, 22)

In [15]:
df.size #rows*cells

220000

In [19]:
df.columns

Index(['Customer_ID', 'Age', 'Gender', 'City', 'Region', 'Income',
       'Credit_Score', 'Account_Balance', 'Tenure_Months', 'Num_Transactions',
       'Avg_Transaction_Amount', 'Total_Spend', 'Product_Type', 'Channel',
       'Satisfaction_Score', 'Complaints', 'Last_Transaction_Date',
       'Is_Active', 'Churn', 'Risk_Band', 'Marketing_Opt_In',
       'Support_Tickets'],
      dtype='str')

In [20]:
df.index

RangeIndex(start=0, stop=10000, step=1)

In [21]:
df.dtypes

Customer_ID                   str
Age                         int64
Gender                        str
City                          str
Region                        str
Income                    float64
Credit_Score              float64
Account_Balance           float64
Tenure_Months               int64
Num_Transactions            int64
Avg_Transaction_Amount    float64
Total_Spend               float64
Product_Type                  str
Channel                       str
Satisfaction_Score        float64
Complaints                  int64
Last_Transaction_Date         str
Is_Active                    bool
Churn                       int64
Risk_Band                     str
Marketing_Opt_In             bool
Support_Tickets             int64
dtype: object

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer_ID             10000 non-null  str
 1   Age                     10000 non-null  int64
 2   Gender                  10000 non-null  str
 3   City                    10000 non-null  str
 4   Region                  10000 non-null  str
 5   Income                  9800 non-null   float64
 6   Credit_Score            9800 non-null   float64
 7   Account_Balance         10000 non-null  float64
 8   Tenure_Months           10000 non-null  int64
 9   Num_Transactions        10000 non-null  int64
 10  Avg_Transaction_Amount  10000 non-null  float64
 11  Total_Spend             10000 non-null  float64
 12  Product_Type            10000 non-null  str
 13  Channel                 10000 non-null  str
 14  Satisfaction_Score      9800 non-null   float64
 15  Complaints              10000 non-null  int64
 16  Last_Transaction_Date   10000 non-null  str
 17  Is_Active               10000 non-null  bool
 18  Churn                   10000 non-null  int64
 19  Risk_Band               10000 non-null  str
 20  Marketing_Opt_In        10000 non-null  bool
 21  Support_Tickets         10000 non-null  int64
dtypes: bool(2), float64(6), int64(6), str(8)
memory usage: 1.5 MB