In [1]:
import pandas as pd

In [2]:
path = r"E:\Data Science\Pandas\customer_analytics_10000.csv"

In [3]:
df = pd.read_csv(path)

In [10]:
df

,Customer_ID,Age,Gender,City,Region,Income,Credit_Score,Account_Balance,Tenure_Months,Num_Transactions,...,Product_Type,Channel,Satisfaction_Score,Complaints,Last_Transaction_Date,Is_Active,Churn,Risk_Band,Marketing_Opt_In,Support_Tickets
0,C00001,23,Other,Hyderabad,South,40823.66,581.0,6084.29,80,12,...,Savings,Web,5.0,1,2025-04-10,True,0,Medium,False,2
1,C00002,62,Male,Delhi,Central,53091.08,805.0,28218.97,196,14,...,Investment,Phone,1.0,0,2024-07-05,True,0,Medium,True,0
2,C00003,55,Male,Delhi,Central,70984.02,421.0,12570.94,42,13,...,Credit Card,Branch,3.0,0,2024-02-09,True,0,Low,False,1
3,C00004,43,Male,Mumbai,South,51176.96,441.0,0.00,37,13,...,Personal Loan,Mobile App,3.0,1,2024-01-08,True,0,High,True,0
4,C00005,43,Unknown,Nagpur,North,58875.94,314.0,20451.36,213,27,...,Savings,Phone,4.0,1,2024-06-18,True,0,Low,True,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,C09996,45,Male,Pune,North,72308.96,NaN,30418.62,161,14,...,Mortgage,Web,5.0,0,2024-09-29,True,0,Medium,True,0
9996,C09997,75,Female,Nagpur,West,51327.02,300.0,29399.98,120,26,...,Savings,Phone,5.0,4,2025-03-11,True,0,High,True,1
9997,C09998,38,Male,Nagpur,South,48316.22,595.0,4564.80,114,11,...,Mortgage,Web,4.0,1,2024-10-09,True,0,Medium,True,1
9998,C09999,50,Unknown,Chennai,West,54334.05,845.0,41852.33,7,19,...,Savings,Mobile App,1.0,2,2024-10-15,True,1,High,True,3
9999,C10000,53,Male,Mumbai,West,81051.77,519.0,0.00,30,19,...,Investment,Branch,2.0,2,2025-05-16,True,0,Low,True,0

In [11]:
df.memory_usage()
#it gives memory usage of each column

Index                       132
Customer_ID               80000
Age                       80000
Gender                    80000
City                      80000
Region                    80000
Income                    80000
Credit_Score              80000
Account_Balance           80000
Tenure_Months             80000
Num_Transactions          80000
Avg_Transaction_Amount    80000
Total_Spend               80000
Product_Type              80000
Channel                   80000
Satisfaction_Score        80000
Complaints                80000
Last_Transaction_Date     80000
Is_Active                 10000
Churn                     80000
Risk_Band                 80000
Marketing_Opt_In          10000
Support_Tickets           80000
dtype: int64

In [12]:
df.memory_usage().sum()

np.int64(1620132)

In [13]:
df.memory_usage(deep=True)
# more detail aestimate of memory usage ,especially for col containing str and python obj

Index                        132
Customer_ID               550000
Age                        80000
Gender                    540792
City                      555910
Region                    542476
Income                     80000
Credit_Score               80000
Account_Balance            80000
Tenure_Months              80000
Num_Transactions           80000
Avg_Transaction_Amount     80000
Total_Spend                80000
Product_Type              588029
Channel                   550139
Satisfaction_Score         80000
Complaints                 80000
Last_Transaction_Date     590000
Is_Active                  10000
Churn                      80000
Risk_Band                 532874
Marketing_Opt_In           10000
Support_Tickets            80000
dtype: int64

In [ ]:
# approx memory
df.memory_usage(deep=True).sum()
#after execution see the diff between deep memory size and normal memory size

np.int64(5430352)

In [15]:
# describe method
df.describe()

,Age,Income,Credit_Score,Account_Balance,Tenure_Months,Num_Transactions,Avg_Transaction_Amount,Total_Spend,Satisfaction_Score,Complaints,Churn,Support_Tickets
count,10000.000000,9800.000000,9800.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,9800.000000,10000.000000,10000.000000,10000.000000
mean,46.288300,64989.377149,574.564898,18780.304584,121.326700,18.042500,162.363479,2927.224463,3.610000,0.699400,0.085700,1.205900
std,16.663179,21992.531643,159.836096,12835.010940,68.849882,4.277794,108.905813,2135.412122,1.168148,0.838517,0.279935,1.109157
min,18.000000,12000.000000,300.000000,0.000000,1.000000,4.000000,5.000000,65.000000,1.000000,0.000000,0.000000,0.000000
25%,32.000000,50272.112500,435.000000,8743.907500,62.000000,15.000000,82.425000,1391.252500,3.000000,0.000000,0.000000,0.000000
50%,46.000000,64508.015000,574.000000,18005.610000,121.000000,18.000000,138.645000,2412.180000,4.000000,1.000000,0.000000,1.000000
75%,61.000000,79713.802500,715.000000,27557.017500,180.000000,21.000000,217.590000,3942.600000,5.000000,1.000000,0.000000,2.000000
max,75.000000,156327.310000,850.000000,86757.620000,240.000000,36.000000,1155.880000,29808.810000,5.000000,5.000000,1.000000,7.000000

In [9]:
df.describe(include="all")

,Customer_ID,Age,Gender,City,Region,Income,Credit_Score,Account_Balance,Tenure_Months,Num_Transactions,...,Product_Type,Channel,Satisfaction_Score,Complaints,Last_Transaction_Date,Is_Active,Churn,Risk_Band,Marketing_Opt_In,Support_Tickets
count,10000,10000.000000,10000,10000,10000,9800.000000,9800.000000,10000.000000,10000.000000,10000.000000,...,10000,10000,9800.000000,10000.000000,10000,10000,10000.000000,10000,10000,10000.000000
unique,10000,NaN,4,7,4,NaN,NaN,NaN,NaN,NaN,...,5,4,NaN,NaN,730,2,NaN,3,2,NaN
top,C00001,NaN,Female,Hyderabad,South,NaN,NaN,NaN,NaN,NaN,...,Savings,Mobile App,NaN,NaN,2025-08-02,True,NaN,Low,True,NaN
freq,1,NaN,4712,1480,2526,NaN,NaN,NaN,NaN,NaN,...,2030,2532,NaN,NaN,29,8211,NaN,4220,6759,NaN
mean,NaN,46.288300,NaN,NaN,NaN,64989.377149,574.564898,18780.304584,121.326700,18.042500,...,NaN,NaN,3.610000,0.699400,NaN,NaN,0.085700,NaN,NaN,1.205900
std,NaN,16.663179,NaN,NaN,NaN,21992.531643,159.836096,12835.010940,68.849882,4.277794,...,NaN,NaN,1.168148,0.838517,NaN,NaN,0.279935,NaN,NaN,1.109157
min,NaN,18.000000,NaN,NaN,NaN,12000.000000,300.000000,0.000000,1.000000,4.000000,...,NaN,NaN,1.000000,0.000000,NaN,NaN,0.000000,NaN,NaN,0.000000
25%,NaN,32.000000,NaN,NaN,NaN,50272.112500,435.000000,8743.907500,62.000000,15.000000,...,NaN,NaN,3.000000,0.000000,NaN,NaN,0.000000,NaN,NaN,0.000000
50%,NaN,46.000000,NaN,NaN,NaN,64508.015000,574.000000,18005.610000,121.000000,18.000000,...,NaN,NaN,4.000000,1.000000,NaN,NaN,0.000000,NaN,NaN,1.000000
75%,NaN,61.000000,NaN,NaN,NaN,79713.802500,715.000000,27557.017500,180.000000,21.000000,...,NaN,NaN,5.000000,1.000000,NaN,NaN,0.000000,NaN,NaN,2.000000
max,NaN,75.000000,NaN,NaN,NaN,156327.310000,850.000000,86757.620000,240.000000,36.000000,...,NaN,NaN,5.000000,5.000000,NaN,NaN,1.000000,NaN,NaN,7.000000

In [16]:
df.nunique()

Customer_ID               10000
Age                          58
Gender                        4
City                          7
Region                        4
Income                     9711
Credit_Score                551
Account_Balance            9060
Tenure_Months               240
Num_Transactions             33
Avg_Transaction_Amount     8559
Total_Spend                9740
Product_Type                  5
Channel                       4
Satisfaction_Score            5
Complaints                    6
Last_Transaction_Date       730
Is_Active                     2
Churn                         2
Risk_Band                     3
Marketing_Opt_In              2
Support_Tickets               8
dtype: int64

In [17]:

dff =df["Age"].nunique()
dff

58

In [18]:
dff =df["Gender"].nunique()
dff

4

In [20]:
df["Gender"].unique()

<StringArray>
['Other', 'Male', 'Unknown', 'Female']
Length: 4, dtype: str

In [19]:
df["Age"].unique()

array([23, 62, 55, 43, 67, 22, 58, 29, 48, 74, 60, 59, 63, 47, 25, 66, 44,
       39, 28, 71, 41, 65, 49, 31, 50, 69, 21, 34, 54, 27, 61, 38, 57, 45,
       46, 20, 26, 36, 70, 64, 37, 56, 72, 40, 18, 32, 24, 51, 35, 52, 19,
       30, 75, 42, 53, 73, 33, 68])

In [ ]:
df["Age"].top()

AttributeError: 'Series' object has no attribute 'top'

In [12]:
# value counts
df['City'].value_counts() 
# frequency of each city calcu

City
Hyderabad    1480
Chennai      1476
Nagpur       1468
Mumbai       1439
Pune         1385
Bengaluru    1379
Delhi        1373
Name: count, dtype: int64

In [23]:
df["Age"].value_counts()

Age
43    205
48    204
45    199
71    197
61    196
32    192
75    192
37    191
67    190
34    190
26    190
64    190
28    188
36    188
23    186
50    186
47    183
62    182
44    181
35    180
53    180
25    179
59    176
55    174
29    174
31    174
49    173
24    173
57    172
41    171
27    171
72    171
42    171
20    170
52    170
60    166
21    166
19    166
22    165
56    165
68    165
18    164
30    162
33    162
66    159
73    157
39    155
65    155
63    154
46    153
40    153
74    152
69    150
58    149
54    145
51    145
38    142
70    141
Name: count, dtype: int64

In [24]:
# Series
ages = pd.Series([35,41,74,85],name="Age")
ages

0    35
1    41
2    74
3    85
Name: Age, dtype: int64

In [25]:
df['Account_Balance'].max()

np.float64(86757.62)

In [26]:
# create a dataframe ### a table 
dff = pd.DataFrame(
    {
        "Name" : ["Ravi","rahul","vj"],
        "Age" : [25,41,16],
        "City" : ["Pune","Mumbai","Kolkata"]
    }
)

In [27]:
dff

    Name  Age     City
0   Ravi   25     Pune
1  rahul   41   Mumbai
2     vj   16  Kolkata

In [28]:
# useful operations
ages.sum()

np.int64(235)

In [29]:
ages.mean()

np.float64(58.75)

In [30]:
# Series
ages = pd.Series([35,41,74,85,85,85,85,85,85],name="Age")
ages
ages.mode()

0    85
Name: Age, dtype: int64

In [31]:
ages.min()

np.int64(35)

In [32]:
ages.max()

np.int64(85)

In [33]:
df["Income"].isna().sum()

np.int64(200)

In [34]:
income = df["Income"]

In [35]:
income

0       40823.66
1       53091.08
2       70984.02
3       51176.96
4       58875.94
          ...
9995    72308.96
9996    51327.02
9997    48316.22
9998    54334.05
9999    81051.77
Name: Income, Length: 10000, dtype: float64

In [36]:
df.columns

Index(['Customer_ID', 'Age', 'Gender', 'City', 'Region', 'Income',
       'Credit_Score', 'Account_Balance', 'Tenure_Months', 'Num_Transactions',
       'Avg_Transaction_Amount', 'Total_Spend', 'Product_Type', 'Channel',
       'Satisfaction_Score', 'Complaints', 'Last_Transaction_Date',
       'Is_Active', 'Churn', 'Risk_Band', 'Marketing_Opt_In',
       'Support_Tickets'],
      dtype='str')

In [38]:
# only take specific columns
subset = df[['Customer_ID', 'Age', 'Gender']]

In [39]:
subset

     Customer_ID  Age   Gender
0         C00001   23    Other
1         C00002   62     Male
2         C00003   55     Male
3         C00004   43     Male
4         C00005   43  Unknown
...          ...  ...      ...
9995      C09996   45     Male
9996      C09997   75   Female
9997      C09998   38     Male
9998      C09999   50  Unknown
9999      C10000   53     Male

[10000 rows x 3 columns]

In [42]:
# Loc
# problem : fetch city and income for customers with income > 75000
res = df[df['Income']>75000]
res

,Customer_ID,Age,Gender,City,Region,Income,Credit_Score,Account_Balance,Tenure_Months,Num_Transactions,...,Product_Type,Channel,Satisfaction_Score,Complaints,Last_Transaction_Date,Is_Active,Churn,Risk_Band,Marketing_Opt_In,Support_Tickets
8,C00009,29,Male,Hyderabad,South,100040.03,459.0,41984.82,100,21,...,Savings,Mobile App,4.0,0,2024-05-15,True,0,High,True,2
10,C00011,48,Male,Delhi,West,90945.43,692.0,20705.47,56,24,...,Personal Loan,Branch,2.0,0,2024-10-11,True,0,Low,True,2
11,C00012,74,Male,Bengaluru,South,77306.14,395.0,21359.40,126,22,...,Personal Loan,Phone,3.0,1,2025-11-24,True,0,Low,False,1
17,C00018,25,Male,Nagpur,West,78522.17,302.0,17184.30,161,14,...,Savings,Phone,3.0,0,2025-02-10,False,0,Low,True,0
18,C00019,66,Male,Nagpur,West,92613.49,812.0,12706.09,221,14,...,Savings,Phone,5.0,0,2024-04-11,True,0,Low,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9986,C09987,46,Male,Pune,North,81827.81,320.0,54529.88,134,21,...,Personal Loan,Web,5.0,1,2024-10-03,True,0,Medium,True,1
9988,C09989,56,Female,Pune,South,104244.85,847.0,26281.98,153,19,...,Credit Card,Web,2.0,1,2024-12-11,True,0,Low,True,1
9990,C09991,36,Other,Hyderabad,South,79661.65,814.0,12792.44,152,21,...,Personal Loan,Mobile App,5.0,0,2024-01-26,True,0,Medium,True,3
9992,C09993,71,Female,Delhi,West,83238.95,780.0,8986.71,96,17,...,Personal Loan,Phone,1.0,0,2024-08-26,True,0,High,True,2
9999,C10000,53,Male,Mumbai,West,81051.77,519.0,0.00,30,19,...,Investment,Branch,2.0,2,2025-05-16,True,0,Low,True,0

In [43]:
# specific cols
res = df.loc[df['Income']>75000,['Customer_ID','City','Income']]
res

     Customer_ID       City     Income
8         C00009  Hyderabad  100040.03
10        C00011      Delhi   90945.43
11        C00012  Bengaluru   77306.14
17        C00018     Nagpur   78522.17
18        C00019     Nagpur   92613.49
...          ...        ...        ...
9986      C09987       Pune   81827.81
9988      C09989       Pune  104244.85
9990      C09991  Hyderabad   79661.65
9992      C09993      Delhi   83238.95
9999      C10000     Mumbai   81051.77

[3156 rows x 3 columns]

In [44]:
# Iloc method
# problem : fetch the first 5 rows and first 6 columns
res = df.iloc[0:5,0:7]
res
# first we define rows - start and end, then we define columns

  Customer_ID  Age   Gender       City   Region    Income  Credit_Score
0      C00001   23    Other  Hyderabad    South  40823.66         581.0
1      C00002   62     Male      Delhi  Central  53091.08         805.0
2      C00003   55     Male      Delhi  Central  70984.02         421.0
3      C00004   43     Male     Mumbai    South  51176.96         441.0
4      C00005   43  Unknown     Nagpur    North  58875.94         314.0

In [45]:
# Iloc method
# problem : fetch the first 5 rows and first 6 columns
res = df.iloc[500:510,2:5]
res
# first we define rows - start and end, then we define columns

     Gender       City   Region
500  Female       Pune    South
501    Male     Nagpur    North
502  Female     Mumbai    North
503  Female     Nagpur  Central
504    Male     Mumbai     West
505  Female  Hyderabad    South
506    Male     Nagpur    North
507   Other      Delhi  Central
508  Female      Delhi    South
509  Female      Delhi    North

In [46]:
df

,Customer_ID,Age,Gender,City,Region,Income,Credit_Score,Account_Balance,Tenure_Months,Num_Transactions,...,Product_Type,Channel,Satisfaction_Score,Complaints,Last_Transaction_Date,Is_Active,Churn,Risk_Band,Marketing_Opt_In,Support_Tickets
0,C00001,23,Other,Hyderabad,South,40823.66,581.0,6084.29,80,12,...,Savings,Web,5.0,1,2025-04-10,True,0,Medium,False,2
1,C00002,62,Male,Delhi,Central,53091.08,805.0,28218.97,196,14,...,Investment,Phone,1.0,0,2024-07-05,True,0,Medium,True,0
2,C00003,55,Male,Delhi,Central,70984.02,421.0,12570.94,42,13,...,Credit Card,Branch,3.0,0,2024-02-09,True,0,Low,False,1
3,C00004,43,Male,Mumbai,South,51176.96,441.0,0.00,37,13,...,Personal Loan,Mobile App,3.0,1,2024-01-08,True,0,High,True,0
4,C00005,43,Unknown,Nagpur,North,58875.94,314.0,20451.36,213,27,...,Savings,Phone,4.0,1,2024-06-18,True,0,Low,True,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,C09996,45,Male,Pune,North,72308.96,NaN,30418.62,161,14,...,Mortgage,Web,5.0,0,2024-09-29,True,0,Medium,True,0
9996,C09997,75,Female,Nagpur,West,51327.02,300.0,29399.98,120,26,...,Savings,Phone,5.0,4,2025-03-11,True,0,High,True,1
9997,C09998,38,Male,Nagpur,South,48316.22,595.0,4564.80,114,11,...,Mortgage,Web,4.0,1,2024-10-09,True,0,Medium,True,1
9998,C09999,50,Unknown,Chennai,West,54334.05,845.0,41852.33,7,19,...,Savings,Mobile App,1.0,2,2024-10-15,True,1,High,True,3
9999,C10000,53,Male,Mumbai,West,81051.77,519.0,0.00,30,19,...,Investment,Branch,2.0,2,2025-05-16,True,0,Low,True,0

In [47]:
df['Is_Active'].unique()
# unique values in that particular column

array([ True, False])

In [48]:
df['Product_Type'].unique()

<StringArray>
['Savings', 'Investment', 'Credit Card', 'Personal Loan', 'Mortgage']
Length: 5, dtype: str

In [49]:
# problem statement
# update the bank account balance for active customers in pune 
df.loc[(df['City']=="Pune") & (df['Is_Active']==True), 'Account_Balance']*=25
### and condition

In [50]:
df

,Customer_ID,Age,Gender,City,Region,Income,Credit_Score,Account_Balance,Tenure_Months,Num_Transactions,...,Product_Type,Channel,Satisfaction_Score,Complaints,Last_Transaction_Date,Is_Active,Churn,Risk_Band,Marketing_Opt_In,Support_Tickets
0,C00001,23,Other,Hyderabad,South,40823.66,581.0,6084.29,80,12,...,Savings,Web,5.0,1,2025-04-10,True,0,Medium,False,2
1,C00002,62,Male,Delhi,Central,53091.08,805.0,28218.97,196,14,...,Investment,Phone,1.0,0,2024-07-05,True,0,Medium,True,0
2,C00003,55,Male,Delhi,Central,70984.02,421.0,12570.94,42,13,...,Credit Card,Branch,3.0,0,2024-02-09,True,0,Low,False,1
3,C00004,43,Male,Mumbai,South,51176.96,441.0,0.00,37,13,...,Personal Loan,Mobile App,3.0,1,2024-01-08,True,0,High,True,0
4,C00005,43,Unknown,Nagpur,North,58875.94,314.0,20451.36,213,27,...,Savings,Phone,4.0,1,2024-06-18,True,0,Low,True,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,C09996,45,Male,Pune,North,72308.96,NaN,760465.50,161,14,...,Mortgage,Web,5.0,0,2024-09-29,True,0,Medium,True,0
9996,C09997,75,Female,Nagpur,West,51327.02,300.0,29399.98,120,26,...,Savings,Phone,5.0,4,2025-03-11,True,0,High,True,1
9997,C09998,38,Male,Nagpur,South,48316.22,595.0,4564.80,114,11,...,Mortgage,Web,4.0,1,2024-10-09,True,0,Medium,True,1
9998,C09999,50,Unknown,Chennai,West,54334.05,845.0,41852.33,7,19,...,Savings,Mobile App,1.0,2,2024-10-15,True,1,High,True,3
9999,C10000,53,Male,Mumbai,West,81051.77,519.0,0.00,30,19,...,Investment,Branch,2.0,2,2025-05-16,True,0,Low,True,0

In [51]:
df.columns

Index(['Customer_ID', 'Age', 'Gender', 'City', 'Region', 'Income',
       'Credit_Score', 'Account_Balance', 'Tenure_Months', 'Num_Transactions',
       'Avg_Transaction_Amount', 'Total_Spend', 'Product_Type', 'Channel',
       'Satisfaction_Score', 'Complaints', 'Last_Transaction_Date',
       'Is_Active', 'Churn', 'Risk_Band', 'Marketing_Opt_In',
       'Support_Tickets'],
      dtype='str')

In [52]:
df['Account_Balance'].min()

np.float64(0.0)

In [53]:
df['Account_Balance'].max()

np.float64(1754151.25)

In [59]:
# Or condition
# pune or mumbai
df.loc[df['City'].isin(['Pune','Mumbai'])]

,Customer_ID,Age,Gender,City,Region,Income,Credit_Score,Account_Balance,Tenure_Months,Num_Transactions,...,Product_Type,Channel,Satisfaction_Score,Complaints,Last_Transaction_Date,Is_Active,Churn,Risk_Band,Marketing_Opt_In,Support_Tickets
3,C00004,43,Male,Mumbai,South,51176.96,441.0,0.00,37,13,...,Personal Loan,Mobile App,3.0,1,2024-01-08,True,0,High,True,0
6,C00007,22,Female,Mumbai,South,57327.00,714.0,24551.21,162,12,...,Mortgage,Mobile App,4.0,3,2024-01-21,False,0,Low,True,0
12,C00013,60,Male,Pune,Central,32720.68,811.0,1066968.75,95,13,...,Mortgage,Web,3.0,1,2025-02-17,True,0,Low,True,2
19,C00020,44,Female,Mumbai,North,71779.85,748.0,24434.85,218,15,...,Mortgage,Mobile App,4.0,2,2024-02-16,True,0,High,True,0
20,C00021,47,Male,Mumbai,Central,55195.05,521.0,0.00,220,20,...,Personal Loan,Branch,5.0,0,2025-02-08,True,0,Medium,False,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9988,C09989,56,Female,Pune,South,104244.85,847.0,657049.50,153,19,...,Credit Card,Web,2.0,1,2024-12-11,True,0,Low,True,1
9993,C09994,27,Male,Mumbai,Central,32955.19,395.0,3964.14,223,13,...,Credit Card,Mobile App,3.0,1,2025-04-13,True,0,Medium,False,2
9994,C09995,73,Male,Mumbai,Central,43344.72,775.0,0.00,16,28,...,Mortgage,Branch,4.0,0,2024-07-30,False,1,High,False,0
9995,C09996,45,Male,Pune,North,72308.96,NaN,760465.50,161,14,...,Mortgage,Web,5.0,0,2024-09-29,True,0,Medium,True,0
9999,C10000,53,Male,Mumbai,West,81051.77,519.0,0.00,30,19,...,Investment,Branch,2.0,2,2025-05-16,True,0,Low,True,0

In [60]:
df['City'].unique()

<StringArray>
['Hyderabad', 'Delhi', 'Mumbai', 'Nagpur', 'Bengaluru', 'Pune', 'Chennai']
Length: 7, dtype: str

In [61]:
df

,Customer_ID,Age,Gender,City,Region,Income,Credit_Score,Account_Balance,Tenure_Months,Num_Transactions,...,Product_Type,Channel,Satisfaction_Score,Complaints,Last_Transaction_Date,Is_Active,Churn,Risk_Band,Marketing_Opt_In,Support_Tickets
0,C00001,23,Other,Hyderabad,South,40823.66,581.0,6084.29,80,12,...,Savings,Web,5.0,1,2025-04-10,True,0,Medium,False,2
1,C00002,62,Male,Delhi,Central,53091.08,805.0,28218.97,196,14,...,Investment,Phone,1.0,0,2024-07-05,True,0,Medium,True,0
2,C00003,55,Male,Delhi,Central,70984.02,421.0,12570.94,42,13,...,Credit Card,Branch,3.0,0,2024-02-09,True,0,Low,False,1
3,C00004,43,Male,Mumbai,South,51176.96,441.0,0.00,37,13,...,Personal Loan,Mobile App,3.0,1,2024-01-08,True,0,High,True,0
4,C00005,43,Unknown,Nagpur,North,58875.94,314.0,20451.36,213,27,...,Savings,Phone,4.0,1,2024-06-18,True,0,Low,True,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,C09996,45,Male,Pune,North,72308.96,NaN,760465.50,161,14,...,Mortgage,Web,5.0,0,2024-09-29,True,0,Medium,True,0
9996,C09997,75,Female,Nagpur,West,51327.02,300.0,29399.98,120,26,...,Savings,Phone,5.0,4,2025-03-11,True,0,High,True,1
9997,C09998,38,Male,Nagpur,South,48316.22,595.0,4564.80,114,11,...,Mortgage,Web,4.0,1,2024-10-09,True,0,Medium,True,1
9998,C09999,50,Unknown,Chennai,West,54334.05,845.0,41852.33,7,19,...,Savings,Mobile App,1.0,2,2024-10-15,True,1,High,True,3
9999,C10000,53,Male,Mumbai,West,81051.77,519.0,0.00,30,19,...,Investment,Branch,2.0,2,2025-05-16,True,0,Low,True,0

In [62]:
# age more than 40
df.loc[df["Age"]>=45]

,Customer_ID,Age,Gender,City,Region,Income,Credit_Score,Account_Balance,Tenure_Months,Num_Transactions,...,Product_Type,Channel,Satisfaction_Score,Complaints,Last_Transaction_Date,Is_Active,Churn,Risk_Band,Marketing_Opt_In,Support_Tickets
1,C00002,62,Male,Delhi,Central,53091.08,805.0,28218.97,196,14,...,Investment,Phone,1.0,0,2024-07-05,True,0,Medium,True,0
2,C00003,55,Male,Delhi,Central,70984.02,421.0,12570.94,42,13,...,Credit Card,Branch,3.0,0,2024-02-09,True,0,Low,False,1
5,C00006,67,Male,Nagpur,West,74709.89,410.0,42149.01,218,15,...,Investment,Web,5.0,2,2025-07-07,True,0,Low,True,0
7,C00008,58,Female,Bengaluru,South,69973.31,367.0,10035.10,81,12,...,Credit Card,Branch,3.0,0,2024-12-04,True,0,Medium,True,1
10,C00011,48,Male,Delhi,West,90945.43,692.0,20705.47,56,24,...,Personal Loan,Branch,2.0,0,2024-10-11,True,0,Low,True,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,C09995,73,Male,Mumbai,Central,43344.72,775.0,0.00,16,28,...,Mortgage,Branch,4.0,0,2024-07-30,False,1,High,False,0
9995,C09996,45,Male,Pune,North,72308.96,NaN,760465.50,161,14,...,Mortgage,Web,5.0,0,2024-09-29,True,0,Medium,True,0
9996,C09997,75,Female,Nagpur,West,51327.02,300.0,29399.98,120,26,...,Savings,Phone,5.0,4,2025-03-11,True,0,High,True,1
9998,C09999,50,Unknown,Chennai,West,54334.05,845.0,41852.33,7,19,...,Savings,Mobile App,1.0,2,2024-10-15,True,1,High,True,3
9999,C10000,53,Male,Mumbai,West,81051.77,519.0,0.00,30,19,...,Investment,Branch,2.0,2,2025-05-16,True,0,Low,True,0

In [63]:
# inclusive range
df.loc[df["Age"].between(25,35)]

,Customer_ID,Age,Gender,City,Region,Income,Credit_Score,Account_Balance,Tenure_Months,Num_Transactions,...,Product_Type,Channel,Satisfaction_Score,Complaints,Last_Transaction_Date,Is_Active,Churn,Risk_Band,Marketing_Opt_In,Support_Tickets
8,C00009,29,Male,Hyderabad,South,100040.03,459.0,41984.82,100,21,...,Savings,Mobile App,4.0,0,2024-05-15,True,0,High,True,2
17,C00018,25,Male,Nagpur,West,78522.17,302.0,17184.30,161,14,...,Savings,Phone,3.0,0,2025-02-10,False,0,Low,True,0
22,C00023,28,Female,Bengaluru,North,66552.97,697.0,374.52,165,15,...,Investment,Web,3.0,0,2024-05-04,True,0,Low,True,0
31,C00032,31,Female,Bengaluru,West,47941.04,425.0,24297.90,87,20,...,Investment,Mobile App,2.0,0,2024-08-08,True,0,Low,True,2
38,C00039,34,Male,Bengaluru,South,63870.46,692.0,13239.72,164,19,...,Mortgage,Phone,2.0,0,2025-07-03,False,0,High,True,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9976,C09977,29,Male,Hyderabad,Central,70087.56,327.0,40493.44,100,17,...,Credit Card,Web,5.0,1,2024-07-02,True,0,High,False,1
9978,C09979,32,Male,Delhi,Central,87068.46,749.0,3480.41,237,16,...,Mortgage,Mobile App,4.0,1,2024-10-25,True,0,High,True,2
9984,C09985,33,Male,Bengaluru,West,63760.06,505.0,10567.75,204,18,...,Credit Card,Branch,3.0,0,2024-07-22,True,0,Low,False,4
9991,C09992,30,Male,Nagpur,North,22998.98,705.0,0.00,50,16,...,Investment,Branch,4.0,0,2024-06-09,True,0,Medium,True,4
9993,C09994,27,Male,Mumbai,Central,32955.19,395.0,3964.14,223,13,...,Credit Card,Mobile App,3.0,1,2025-04-13,True,0,Medium,False,2

In [64]:
# not equal to # people not equal to pune
df.loc[df["City"]!= "Pune"]

,Customer_ID,Age,Gender,City,Region,Income,Credit_Score,Account_Balance,Tenure_Months,Num_Transactions,...,Product_Type,Channel,Satisfaction_Score,Complaints,Last_Transaction_Date,Is_Active,Churn,Risk_Band,Marketing_Opt_In,Support_Tickets
0,C00001,23,Other,Hyderabad,South,40823.66,581.0,6084.29,80,12,...,Savings,Web,5.0,1,2025-04-10,True,0,Medium,False,2
1,C00002,62,Male,Delhi,Central,53091.08,805.0,28218.97,196,14,...,Investment,Phone,1.0,0,2024-07-05,True,0,Medium,True,0
2,C00003,55,Male,Delhi,Central,70984.02,421.0,12570.94,42,13,...,Credit Card,Branch,3.0,0,2024-02-09,True,0,Low,False,1
3,C00004,43,Male,Mumbai,South,51176.96,441.0,0.00,37,13,...,Personal Loan,Mobile App,3.0,1,2024-01-08,True,0,High,True,0
4,C00005,43,Unknown,Nagpur,North,58875.94,314.0,20451.36,213,27,...,Savings,Phone,4.0,1,2024-06-18,True,0,Low,True,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,C09995,73,Male,Mumbai,Central,43344.72,775.0,0.00,16,28,...,Mortgage,Branch,4.0,0,2024-07-30,False,1,High,False,0
9996,C09997,75,Female,Nagpur,West,51327.02,300.0,29399.98,120,26,...,Savings,Phone,5.0,4,2025-03-11,True,0,High,True,1
9997,C09998,38,Male,Nagpur,South,48316.22,595.0,4564.80,114,11,...,Mortgage,Web,4.0,1,2024-10-09,True,0,Medium,True,1
9998,C09999,50,Unknown,Chennai,West,54334.05,845.0,41852.33,7,19,...,Savings,Mobile App,1.0,2,2024-10-15,True,1,High,True,3
9999,C10000,53,Male,Mumbai,West,81051.77,519.0,0.00,30,19,...,Investment,Branch,2.0,2,2025-05-16,True,0,Low,True,0

In [65]:
df['Income'].isna().sum()

np.int64(200)

In [66]:
# non missing values
df.loc[df['Income'].notna()]

,Customer_ID,Age,Gender,City,Region,Income,Credit_Score,Account_Balance,Tenure_Months,Num_Transactions,...,Product_Type,Channel,Satisfaction_Score,Complaints,Last_Transaction_Date,Is_Active,Churn,Risk_Band,Marketing_Opt_In,Support_Tickets
0,C00001,23,Other,Hyderabad,South,40823.66,581.0,6084.29,80,12,...,Savings,Web,5.0,1,2025-04-10,True,0,Medium,False,2
1,C00002,62,Male,Delhi,Central,53091.08,805.0,28218.97,196,14,...,Investment,Phone,1.0,0,2024-07-05,True,0,Medium,True,0
2,C00003,55,Male,Delhi,Central,70984.02,421.0,12570.94,42,13,...,Credit Card,Branch,3.0,0,2024-02-09,True,0,Low,False,1
3,C00004,43,Male,Mumbai,South,51176.96,441.0,0.00,37,13,...,Personal Loan,Mobile App,3.0,1,2024-01-08,True,0,High,True,0
4,C00005,43,Unknown,Nagpur,North,58875.94,314.0,20451.36,213,27,...,Savings,Phone,4.0,1,2024-06-18,True,0,Low,True,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,C09996,45,Male,Pune,North,72308.96,NaN,760465.50,161,14,...,Mortgage,Web,5.0,0,2024-09-29,True,0,Medium,True,0
9996,C09997,75,Female,Nagpur,West,51327.02,300.0,29399.98,120,26,...,Savings,Phone,5.0,4,2025-03-11,True,0,High,True,1
9997,C09998,38,Male,Nagpur,South,48316.22,595.0,4564.80,114,11,...,Mortgage,Web,4.0,1,2024-10-09,True,0,Medium,True,1
9998,C09999,50,Unknown,Chennai,West,54334.05,845.0,41852.33,7,19,...,Savings,Mobile App,1.0,2,2024-10-15,True,1,High,True,3
9999,C10000,53,Male,Mumbai,West,81051.77,519.0,0.00,30,19,...,Investment,Branch,2.0,2,2025-05-16,True,0,Low,True,0

In [67]:
# combine condition
# i want only cities pune and mumbai in my data, and income more than 40000 and he should be Marketing_Opt_In true
df.loc[
    (df['City'].isin(["Pune","Mumbai"])) 
    &
    (df['Income'] > 40000)
    &
    (df['Marketing_Opt_In']==True)
]

,Customer_ID,Age,Gender,City,Region,Income,Credit_Score,Account_Balance,Tenure_Months,Num_Transactions,...,Product_Type,Channel,Satisfaction_Score,Complaints,Last_Transaction_Date,Is_Active,Churn,Risk_Band,Marketing_Opt_In,Support_Tickets
3,C00004,43,Male,Mumbai,South,51176.96,441.0,0.00,37,13,...,Personal Loan,Mobile App,3.0,1,2024-01-08,True,0,High,True,0
6,C00007,22,Female,Mumbai,South,57327.00,714.0,24551.21,162,12,...,Mortgage,Mobile App,4.0,3,2024-01-21,False,0,Low,True,0
19,C00020,44,Female,Mumbai,North,71779.85,748.0,24434.85,218,15,...,Mortgage,Mobile App,4.0,2,2024-02-16,True,0,High,True,0
23,C00024,71,Male,Mumbai,Central,65566.94,403.0,0.00,177,23,...,Credit Card,Mobile App,1.0,2,2025-05-11,True,0,Low,True,0
33,C00034,50,Female,Mumbai,Central,72851.99,415.0,27310.52,193,19,...,Savings,Mobile App,2.0,3,2025-08-02,False,0,Low,True,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9985,C09986,58,Female,Mumbai,South,52705.48,823.0,0.00,29,13,...,Personal Loan,Web,3.0,1,2024-05-04,True,0,High,True,0
9986,C09987,46,Male,Pune,North,81827.81,320.0,1363247.00,134,21,...,Personal Loan,Web,5.0,1,2024-10-03,True,0,Medium,True,1
9988,C09989,56,Female,Pune,South,104244.85,847.0,657049.50,153,19,...,Credit Card,Web,2.0,1,2024-12-11,True,0,Low,True,1
9995,C09996,45,Male,Pune,North,72308.96,NaN,760465.50,161,14,...,Mortgage,Web,5.0,0,2024-09-29,True,0,Medium,True,0
9999,C10000,53,Male,Mumbai,West,81051.77,519.0,0.00,30,19,...,Investment,Branch,2.0,2,2025-05-16,True,0,Low,True,0

In [68]:
# keep top rows after sorting
df.nlargest(15,"Total_Spend")

,Customer_ID,Age,Gender,City,Region,Income,Credit_Score,Account_Balance,Tenure_Months,Num_Transactions,...,Product_Type,Channel,Satisfaction_Score,Complaints,Last_Transaction_Date,Is_Active,Churn,Risk_Band,Marketing_Opt_In,Support_Tickets
2324,C02325,61,Other,Bengaluru,West,66618.96,317.0,30524.08,86,29,...,Mortgage,Branch,2.0,0,2024-07-11,False,0,High,True,1
9247,C09248,70,Female,Hyderabad,South,50257.12,777.0,9337.56,107,27,...,Savings,Phone,5.0,1,2024-09-24,True,0,High,True,0
9528,C09529,27,Male,Mumbai,Central,80202.82,552.0,0.00,120,24,...,Personal Loan,Branch,4.0,1,2025-05-13,True,0,Low,False,1
8615,C08616,37,Female,Pune,North,57576.63,388.0,0.00,217,17,...,Mortgage,Web,1.0,2,2025-03-27,True,0,Low,False,1
9618,C09619,41,Male,Bengaluru,West,43776.15,726.0,23675.75,231,31,...,Credit Card,Web,5.0,1,2025-02-26,True,0,Low,False,1
9440,C09441,42,Male,Nagpur,South,124138.47,360.0,13111.10,145,27,...,Investment,Web,2.0,2,2024-11-15,True,0,Low,True,1
3873,C03874,45,Male,Chennai,South,108350.78,756.0,24180.86,44,31,...,Investment,Branch,2.0,1,2025-09-28,True,0,Medium,False,0
7787,C07788,48,Unknown,Pune,Central,53751.77,758.0,121638.75,178,22,...,Credit Card,Phone,5.0,1,2025-11-02,True,0,Low,True,0
1321,C01322,33,Male,Mumbai,West,97789.72,704.0,49146.19,210,24,...,Investment,Branch,4.0,0,2024-12-23,True,0,Medium,False,0
4096,C04097,49,Male,Pune,North,101205.90,661.0,613549.75,69,34,...,Investment,Mobile App,3.0,1,2025-11-03,True,0,High,True,2
5241,C05242,68,Female,Nagpur,Central,42779.77,424.0,13712.97,14,30,...,Credit Card,Branch,3.0,0,2024-03-25,True,0,High,True,1
5622,C05623,29,Male,Nagpur,West,59426.54,676.0,44881.53,15,18,...,Personal Loan,Mobile App,2.0,1,2024-05-28,True,0,Low,True,4
8483,C08484,66,Male,Chennai,North,68552.55,345.0,8485.03,22,28,...,Mortgage,Branch,3.0,1,2025-04-03,True,0,Medium,False,0
77,C00078,31,Male,Chennai,South,66761.82,669.0,34995.10,219,27,...,Investment,Branch,4.0,0,2025-05-31,True,0,Low,True,1
5019,C05020,55,Male,Hyderabad,Central,98603.95,466.0,16132.10,17,23,...,Savings,Branch,5.0,0,2024-06-24,True,0,Medium,False,1

In [69]:
df.columns

Index(['Customer_ID', 'Age', 'Gender', 'City', 'Region', 'Income',
       'Credit_Score', 'Account_Balance', 'Tenure_Months', 'Num_Transactions',
       'Avg_Transaction_Amount', 'Total_Spend', 'Product_Type', 'Channel',
       'Satisfaction_Score', 'Complaints', 'Last_Transaction_Date',
       'Is_Active', 'Churn', 'Risk_Band', 'Marketing_Opt_In',
       'Support_Tickets'],
      dtype='str')

In [70]:
# calculated condition
# mean
df.loc[df['Total_Spend']>df["Total_Spend"].mean()]

,Customer_ID,Age,Gender,City,Region,Income,Credit_Score,Account_Balance,Tenure_Months,Num_Transactions,...,Product_Type,Channel,Satisfaction_Score,Complaints,Last_Transaction_Date,Is_Active,Churn,Risk_Band,Marketing_Opt_In,Support_Tickets
4,C00005,43,Unknown,Nagpur,North,58875.94,314.0,20451.36,213,27,...,Savings,Phone,4.0,1,2024-06-18,True,0,Low,True,0
5,C00006,67,Male,Nagpur,West,74709.89,410.0,42149.01,218,15,...,Investment,Web,5.0,2,2025-07-07,True,0,Low,True,0
10,C00011,48,Male,Delhi,West,90945.43,692.0,20705.47,56,24,...,Personal Loan,Branch,2.0,0,2024-10-11,True,0,Low,True,2
11,C00012,74,Male,Bengaluru,South,77306.14,395.0,21359.40,126,22,...,Personal Loan,Phone,3.0,1,2025-11-24,True,0,Low,False,1
12,C00013,60,Male,Pune,Central,32720.68,811.0,1066968.75,95,13,...,Mortgage,Web,3.0,1,2025-02-17,True,0,Low,True,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9987,C09988,38,Female,Delhi,North,NaN,716.0,20756.80,87,18,...,Mortgage,Web,4.0,0,2025-05-21,True,0,Low,True,1
9990,C09991,36,Other,Hyderabad,South,79661.65,814.0,12792.44,152,21,...,Personal Loan,Mobile App,5.0,0,2024-01-26,True,0,Medium,True,3
9992,C09993,71,Female,Delhi,West,83238.95,780.0,8986.71,96,17,...,Personal Loan,Phone,1.0,0,2024-08-26,True,0,High,True,2
9994,C09995,73,Male,Mumbai,Central,43344.72,775.0,0.00,16,28,...,Mortgage,Branch,4.0,0,2024-07-30,False,1,High,False,0
9996,C09997,75,Female,Nagpur,West,51327.02,300.0,29399.98,120,26,...,Savings,Phone,5.0,4,2025-03-11,True,0,High,True,1

# sorting and ranking

In [71]:
# sort values according to income
df.sort_values("Income")

,Customer_ID,Age,Gender,City,Region,Income,Credit_Score,Account_Balance,Tenure_Months,Num_Transactions,...,Product_Type,Channel,Satisfaction_Score,Complaints,Last_Transaction_Date,Is_Active,Churn,Risk_Band,Marketing_Opt_In,Support_Tickets
6764,C06765,45,Female,Chennai,South,12000.0,521.0,33499.62,221,17,...,Personal Loan,Mobile App,4.0,0,2024-02-25,False,0,Medium,True,3
1948,C01949,18,Male,Pune,North,12000.0,549.0,289610.75,87,27,...,Credit Card,Web,5.0,2,2025-08-06,True,0,Low,True,1
94,C00095,70,Female,Mumbai,West,12000.0,822.0,24329.49,203,20,...,Personal Loan,Web,5.0,1,2024-09-13,True,0,Medium,True,1
3738,C03739,56,Female,Hyderabad,South,12000.0,674.0,24177.68,19,16,...,Personal Loan,Phone,5.0,0,2024-11-05,True,0,Low,False,1
2936,C02937,62,Female,Chennai,North,12000.0,386.0,31784.97,209,18,...,Investment,Phone,3.0,0,2025-08-23,False,0,Medium,False,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9705,C09706,64,Male,Hyderabad,Central,NaN,771.0,40443.50,137,13,...,Savings,Phone,5.0,0,2024-09-22,False,0,Low,False,3
9878,C09879,48,Male,Chennai,Central,NaN,656.0,27082.86,230,22,...,Mortgage,Phone,5.0,0,2025-07-08,True,0,Low,True,1
9879,C09880,28,Other,Mumbai,South,NaN,720.0,49884.81,233,20,...,Savings,Web,3.0,1,2025-12-27,True,0,Medium,True,0
9941,C09942,54,Unknown,Hyderabad,North,NaN,416.0,6392.11,83,22,...,Mortgage,Web,5.0,0,2024-09-22,True,0,Medium,True,2
9987,C09988,38,Female,Delhi,North,NaN,716.0,20756.80,87,18,...,Mortgage,Web,4.0,0,2025-05-21,True,0,Low,True,1

In [72]:
df.sort_values("Income", ascending=False) # if you want for decending

,Customer_ID,Age,Gender,City,Region,Income,Credit_Score,Account_Balance,Tenure_Months,Num_Transactions,...,Product_Type,Channel,Satisfaction_Score,Complaints,Last_Transaction_Date,Is_Active,Churn,Risk_Band,Marketing_Opt_In,Support_Tickets
6710,C06711,35,Male,Hyderabad,South,156327.31,480.0,21238.26,73,15,...,Investment,Web,2.0,1,2024-09-07,True,0,Low,True,0
3212,C03213,37,Female,Delhi,North,153568.13,408.0,0.00,19,19,...,Savings,Web,5.0,0,2024-09-04,True,0,Medium,True,0
4168,C04169,47,Male,Mumbai,South,140590.41,768.0,58850.56,71,12,...,Savings,Mobile App,5.0,2,2025-07-21,True,0,Low,False,2
2259,C02260,75,Male,Bengaluru,North,137464.79,786.0,28926.29,124,13,...,Investment,Branch,5.0,0,2025-12-09,True,1,High,True,0
367,C00368,36,Male,Pune,North,136307.70,503.0,35227.25,24,16,...,Mortgage,Branch,5.0,2,2025-10-18,False,0,Low,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9705,C09706,64,Male,Hyderabad,Central,NaN,771.0,40443.50,137,13,...,Savings,Phone,5.0,0,2024-09-22,False,0,Low,False,3
9878,C09879,48,Male,Chennai,Central,NaN,656.0,27082.86,230,22,...,Mortgage,Phone,5.0,0,2025-07-08,True,0,Low,True,1
9879,C09880,28,Other,Mumbai,South,NaN,720.0,49884.81,233,20,...,Savings,Web,3.0,1,2025-12-27,True,0,Medium,True,0
9941,C09942,54,Unknown,Hyderabad,North,NaN,416.0,6392.11,83,22,...,Mortgage,Web,5.0,0,2024-09-22,True,0,Medium,True,2
9987,C09988,38,Female,Delhi,North,NaN,716.0,20756.80,87,18,...,Mortgage,Web,4.0,0,2025-05-21,True,0,Low,True,1

In [73]:
df.sort_values(["Income","Credit_Score"], ascending=[False,True]) 
# desc according to income and asc according to credit score

,Customer_ID,Age,Gender,City,Region,Income,Credit_Score,Account_Balance,Tenure_Months,Num_Transactions,...,Product_Type,Channel,Satisfaction_Score,Complaints,Last_Transaction_Date,Is_Active,Churn,Risk_Band,Marketing_Opt_In,Support_Tickets
6710,C06711,35,Male,Hyderabad,South,156327.31,480.0,21238.26,73,15,...,Investment,Web,2.0,1,2024-09-07,True,0,Low,True,0
3212,C03213,37,Female,Delhi,North,153568.13,408.0,0.00,19,19,...,Savings,Web,5.0,0,2024-09-04,True,0,Medium,True,0
4168,C04169,47,Male,Mumbai,South,140590.41,768.0,58850.56,71,12,...,Savings,Mobile App,5.0,2,2025-07-21,True,0,Low,False,2
2259,C02260,75,Male,Bengaluru,North,137464.79,786.0,28926.29,124,13,...,Investment,Branch,5.0,0,2025-12-09,True,1,High,True,0
367,C00368,36,Male,Pune,North,136307.70,503.0,35227.25,24,16,...,Mortgage,Branch,5.0,2,2025-10-18,False,0,Low,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2694,C02695,72,Male,Hyderabad,South,NaN,NaN,0.00,142,12,...,Savings,Branch,2.0,1,2024-01-21,True,0,Medium,True,2
4929,C04930,30,Male,Pune,South,NaN,NaN,354990.50,174,20,...,Credit Card,Phone,1.0,0,2025-02-01,True,0,Low,True,2
8247,C08248,40,Female,Nagpur,South,NaN,NaN,18391.67,97,17,...,Credit Card,Branch,5.0,0,2024-07-08,True,0,Low,False,0
9065,C09066,55,Female,Bengaluru,Central,NaN,NaN,17630.71,120,13,...,Credit Card,Web,2.0,0,2025-05-30,True,0,Medium,True,1
9204,C09205,55,Female,Pune,West,NaN,NaN,1249382.50,108,22,...,Credit Card,Web,2.0,1,2025-01-31,True,0,Low,True,2

In [74]:
df.sort_values(["City","Credit_Score"], ascending=[False,False]) 
# desc according to income and asc according to credit score

,Customer_ID,Age,Gender,City,Region,Income,Credit_Score,Account_Balance,Tenure_Months,Num_Transactions,...,Product_Type,Channel,Satisfaction_Score,Complaints,Last_Transaction_Date,Is_Active,Churn,Risk_Band,Marketing_Opt_In,Support_Tickets
1259,C01260,64,Male,Pune,South,61997.58,850.0,415644.25,184,14,...,Savings,Phone,3.0,0,2024-05-02,True,0,Low,True,0
2311,C02312,21,Female,Pune,North,53363.65,850.0,530704.75,113,10,...,Investment,Web,5.0,0,2025-11-24,True,0,Low,True,0
6383,C06384,19,Male,Pune,South,69966.66,850.0,535784.00,47,22,...,Mortgage,Mobile App,2.0,0,2025-12-05,True,0,Low,True,1
7154,C07155,42,Female,Pune,West,79857.01,850.0,380792.00,61,16,...,Credit Card,Mobile App,4.0,0,2024-10-16,True,0,Medium,False,1
9007,C09008,44,Male,Pune,Central,72794.93,850.0,186225.25,141,16,...,Mortgage,Mobile App,3.0,3,2025-09-02,True,0,Low,True,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9065,C09066,55,Female,Bengaluru,Central,NaN,NaN,17630.71,120,13,...,Credit Card,Web,2.0,0,2025-05-30,True,0,Medium,True,1
9331,C09332,41,Female,Bengaluru,North,69002.78,NaN,28347.34,2,25,...,Personal Loan,Phone,4.0,2,2025-12-18,False,0,High,True,0
9386,C09387,64,Male,Bengaluru,West,52766.96,NaN,14853.89,111,14,...,Credit Card,Branch,4.0,0,2024-05-15,True,0,Medium,True,1
9840,C09841,75,Male,Bengaluru,Central,77278.01,NaN,5.14,95,14,...,Mortgage,Web,2.0,0,2025-12-29,False,0,Medium,True,2
9888,C09889,72,Male,Bengaluru,South,53311.99,NaN,0.00,61,25,...,Credit Card,Mobile App,4.0,1,2024-06-03,True,0,Low,True,2

In [75]:
df.sort_values(["City","Credit_Score"], ascending=[False,True]) 
# desc according to income and asc according to credit score

,Customer_ID,Age,Gender,City,Region,Income,Credit_Score,Account_Balance,Tenure_Months,Num_Transactions,...,Product_Type,Channel,Satisfaction_Score,Complaints,Last_Transaction_Date,Is_Active,Churn,Risk_Band,Marketing_Opt_In,Support_Tickets
1650,C01651,29,Female,Pune,West,13392.66,300.0,419003.50,115,30,...,Savings,Mobile App,4.0,0,2024-01-21,True,1,High,True,0
4550,C04551,20,Female,Pune,South,36440.50,300.0,28895.64,71,20,...,Savings,Phone,3.0,0,2025-02-16,False,0,Low,True,2
905,C00906,59,Other,Pune,North,63769.39,302.0,384430.50,176,19,...,Savings,Web,4.0,0,2024-02-05,True,0,High,False,1
8998,C08999,23,Male,Pune,West,69505.22,302.0,346291.50,187,15,...,Savings,Branch,1.0,0,2025-12-24,True,0,Low,True,2
6651,C06652,67,Female,Pune,Central,73361.52,303.0,486948.00,61,16,...,Investment,Branch,4.0,1,2024-07-21,True,1,High,True,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9065,C09066,55,Female,Bengaluru,Central,NaN,NaN,17630.71,120,13,...,Credit Card,Web,2.0,0,2025-05-30,True,0,Medium,True,1
9331,C09332,41,Female,Bengaluru,North,69002.78,NaN,28347.34,2,25,...,Personal Loan,Phone,4.0,2,2025-12-18,False,0,High,True,0
9386,C09387,64,Male,Bengaluru,West,52766.96,NaN,14853.89,111,14,...,Credit Card,Branch,4.0,0,2024-05-15,True,0,Medium,True,1
9840,C09841,75,Male,Bengaluru,Central,77278.01,NaN,5.14,95,14,...,Mortgage,Web,2.0,0,2025-12-29,False,0,Medium,True,2
9888,C09889,72,Male,Bengaluru,South,53311.99,NaN,0.00,61,25,...,Credit Card,Mobile App,4.0,1,2024-06-03,True,0,Low,True,2

In [76]:
import numpy as np

In [77]:
# create a column - derived cols
# person per transaction kitna spend kiya
df['Spend_Per_Transaction'] = (
    df['Total_Spend'] / df['Num_Transactions'].replace(0,np.nan)
)

In [78]:
df

,Customer_ID,Age,Gender,City,Region,Income,Credit_Score,Account_Balance,Tenure_Months,Num_Transactions,...,Channel,Satisfaction_Score,Complaints,Last_Transaction_Date,Is_Active,Churn,Risk_Band,Marketing_Opt_In,Support_Tickets,Spend_Per_Transaction
0,C00001,23,Other,Hyderabad,South,40823.66,581.0,6084.29,80,12,...,Web,5.0,1,2025-04-10,True,0,Medium,False,2,53.31
1,C00002,62,Male,Delhi,Central,53091.08,805.0,28218.97,196,14,...,Phone,1.0,0,2024-07-05,True,0,Medium,True,0,134.93
2,C00003,55,Male,Delhi,Central,70984.02,421.0,12570.94,42,13,...,Branch,3.0,0,2024-02-09,True,0,Low,False,1,224.81
3,C00004,43,Male,Mumbai,South,51176.96,441.0,0.00,37,13,...,Mobile App,3.0,1,2024-01-08,True,0,High,True,0,64.94
4,C00005,43,Unknown,Nagpur,North,58875.94,314.0,20451.36,213,27,...,Phone,4.0,1,2024-06-18,True,0,Low,True,0,136.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,C09996,45,Male,Pune,North,72308.96,NaN,760465.50,161,14,...,Web,5.0,0,2024-09-29,True,0,Medium,True,0,121.97
9996,C09997,75,Female,Nagpur,West,51327.02,300.0,29399.98,120,26,...,Phone,5.0,4,2025-03-11,True,0,High,True,1,205.97
9997,C09998,38,Male,Nagpur,South,48316.22,595.0,4564.80,114,11,...,Web,4.0,1,2024-10-09,True,0,Medium,True,1,137.21
9998,C09999,50,Unknown,Chennai,West,54334.05,845.0,41852.33,7,19,...,Mobile App,1.0,2,2024-10-15,True,1,High,True,3,121.61
9999,C10000,53,Male,Mumbai,West,81051.77,519.0,0.00,30,19,...,Branch,2.0,2,2025-05-16,True,0,Low,True,0,138.34

In [77]:
# rename a column city to customer city
df = df.rename(columns={"City" : "Cusomer_City"})

In [78]:
df

,Customer_ID,Age,Gender,Cusomer_City,Region,Income,Credit_Score,Account_Balance,Tenure_Months,Num_Transactions,...,Channel,Satisfaction_Score,Complaints,Last_Transaction_Date,Is_Active,Churn,Risk_Band,Marketing_Opt_In,Support_Tickets,Spend_Per_Transaction
0,C00001,23,Other,Hyderabad,South,40823.66,581.0,6084.29,80,12,...,Web,5.0,1,2025-04-10,True,0,Medium,False,2,53.31
1,C00002,62,Male,Delhi,Central,53091.08,805.0,28218.97,196,14,...,Phone,1.0,0,2024-07-05,True,0,Medium,True,0,134.93
2,C00003,55,Male,Delhi,Central,70984.02,421.0,12570.94,42,13,...,Branch,3.0,0,2024-02-09,True,0,Low,False,1,224.81
3,C00004,43,Male,Mumbai,South,51176.96,441.0,0.00,37,13,...,Mobile App,3.0,1,2024-01-08,True,0,High,True,0,64.94
4,C00005,43,Unknown,Nagpur,North,58875.94,314.0,20451.36,213,27,...,Phone,4.0,1,2024-06-18,True,0,Low,True,0,136.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,C09996,45,Male,Pune,North,72308.96,NaN,30418.62,161,14,...,Web,5.0,0,2024-09-29,True,0,Medium,True,0,121.97
9996,C09997,75,Female,Nagpur,West,51327.02,300.0,29399.98,120,26,...,Phone,5.0,4,2025-03-11,True,0,High,True,1,205.97
9997,C09998,38,Male,Nagpur,South,48316.22,595.0,4564.80,114,11,...,Web,4.0,1,2024-10-09,True,0,Medium,True,1,137.21
9998,C09999,50,Unknown,Chennai,West,54334.05,845.0,41852.33,7,19,...,Mobile App,1.0,2,2024-10-15,True,1,High,True,3,121.61
9999,C10000,53,Male,Mumbai,West,81051.77,519.0,0.00,30,19,...,Branch,2.0,2,2025-05-16,True,0,Low,True,0,138.34

In [80]:
df = df.rename(columns={"City" : "Customer_City"})

In [81]:
df

,Customer_ID,Age,Gender,Cusomer_City,Region,Income,Credit_Score,Account_Balance,Tenure_Months,Num_Transactions,...,Channel,Satisfaction_Score,Complaints,Last_Transaction_Date,Is_Active,Churn,Risk_Band,Marketing_Opt_In,Support_Tickets,Spend_Per_Transaction
0,C00001,23,Other,Hyderabad,South,40823.66,581.0,6084.29,80,12,...,Web,5.0,1,2025-04-10,True,0,Medium,False,2,53.31
1,C00002,62,Male,Delhi,Central,53091.08,805.0,28218.97,196,14,...,Phone,1.0,0,2024-07-05,True,0,Medium,True,0,134.93
2,C00003,55,Male,Delhi,Central,70984.02,421.0,12570.94,42,13,...,Branch,3.0,0,2024-02-09,True,0,Low,False,1,224.81
3,C00004,43,Male,Mumbai,South,51176.96,441.0,0.00,37,13,...,Mobile App,3.0,1,2024-01-08,True,0,High,True,0,64.94
4,C00005,43,Unknown,Nagpur,North,58875.94,314.0,20451.36,213,27,...,Phone,4.0,1,2024-06-18,True,0,Low,True,0,136.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,C09996,45,Male,Pune,North,72308.96,NaN,30418.62,161,14,...,Web,5.0,0,2024-09-29,True,0,Medium,True,0,121.97
9996,C09997,75,Female,Nagpur,West,51327.02,300.0,29399.98,120,26,...,Phone,5.0,4,2025-03-11,True,0,High,True,1,205.97
9997,C09998,38,Male,Nagpur,South,48316.22,595.0,4564.80,114,11,...,Web,4.0,1,2024-10-09,True,0,Medium,True,1,137.21
9998,C09999,50,Unknown,Chennai,West,54334.05,845.0,41852.33,7,19,...,Mobile App,1.0,2,2024-10-15,True,1,High,True,3,121.61
9999,C10000,53,Male,Mumbai,West,81051.77,519.0,0.00,30,19,...,Branch,2.0,2,2025-05-16,True,0,Low,True,0,138.34

In [82]:
df = df.rename(columns={"Cusomer_City" : "Customer_City"})

In [83]:
df

,Customer_ID,Age,Gender,Customer_City,Region,Income,Credit_Score,Account_Balance,Tenure_Months,Num_Transactions,...,Channel,Satisfaction_Score,Complaints,Last_Transaction_Date,Is_Active,Churn,Risk_Band,Marketing_Opt_In,Support_Tickets,Spend_Per_Transaction
0,C00001,23,Other,Hyderabad,South,40823.66,581.0,6084.29,80,12,...,Web,5.0,1,2025-04-10,True,0,Medium,False,2,53.31
1,C00002,62,Male,Delhi,Central,53091.08,805.0,28218.97,196,14,...,Phone,1.0,0,2024-07-05,True,0,Medium,True,0,134.93
2,C00003,55,Male,Delhi,Central,70984.02,421.0,12570.94,42,13,...,Branch,3.0,0,2024-02-09,True,0,Low,False,1,224.81
3,C00004,43,Male,Mumbai,South,51176.96,441.0,0.00,37,13,...,Mobile App,3.0,1,2024-01-08,True,0,High,True,0,64.94
4,C00005,43,Unknown,Nagpur,North,58875.94,314.0,20451.36,213,27,...,Phone,4.0,1,2024-06-18,True,0,Low,True,0,136.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,C09996,45,Male,Pune,North,72308.96,NaN,30418.62,161,14,...,Web,5.0,0,2024-09-29,True,0,Medium,True,0,121.97
9996,C09997,75,Female,Nagpur,West,51327.02,300.0,29399.98,120,26,...,Phone,5.0,4,2025-03-11,True,0,High,True,1,205.97
9997,C09998,38,Male,Nagpur,South,48316.22,595.0,4564.80,114,11,...,Web,4.0,1,2024-10-09,True,0,Medium,True,1,137.21
9998,C09999,50,Unknown,Chennai,West,54334.05,845.0,41852.33,7,19,...,Mobile App,1.0,2,2024-10-15,True,1,High,True,3,121.61
9999,C10000,53,Male,Mumbai,West,81051.77,519.0,0.00,30,19,...,Branch,2.0,2,2025-05-16,True,0,Low,True,0,138.34

In [84]:
# remove columns
df = df.drop(columns = ["Spend_Per_Transaction"]) #,errors = "ignore"

In [85]:
df

,Customer_ID,Age,Gender,Customer_City,Region,Income,Credit_Score,Account_Balance,Tenure_Months,Num_Transactions,...,Product_Type,Channel,Satisfaction_Score,Complaints,Last_Transaction_Date,Is_Active,Churn,Risk_Band,Marketing_Opt_In,Support_Tickets
0,C00001,23,Other,Hyderabad,South,40823.66,581.0,6084.29,80,12,...,Savings,Web,5.0,1,2025-04-10,True,0,Medium,False,2
1,C00002,62,Male,Delhi,Central,53091.08,805.0,28218.97,196,14,...,Investment,Phone,1.0,0,2024-07-05,True,0,Medium,True,0
2,C00003,55,Male,Delhi,Central,70984.02,421.0,12570.94,42,13,...,Credit Card,Branch,3.0,0,2024-02-09,True,0,Low,False,1
3,C00004,43,Male,Mumbai,South,51176.96,441.0,0.00,37,13,...,Personal Loan,Mobile App,3.0,1,2024-01-08,True,0,High,True,0
4,C00005,43,Unknown,Nagpur,North,58875.94,314.0,20451.36,213,27,...,Savings,Phone,4.0,1,2024-06-18,True,0,Low,True,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,C09996,45,Male,Pune,North,72308.96,NaN,30418.62,161,14,...,Mortgage,Web,5.0,0,2024-09-29,True,0,Medium,True,0
9996,C09997,75,Female,Nagpur,West,51327.02,300.0,29399.98,120,26,...,Savings,Phone,5.0,4,2025-03-11,True,0,High,True,1
9997,C09998,38,Male,Nagpur,South,48316.22,595.0,4564.80,114,11,...,Mortgage,Web,4.0,1,2024-10-09,True,0,Medium,True,1
9998,C09999,50,Unknown,Chennai,West,54334.05,845.0,41852.33,7,19,...,Savings,Mobile App,1.0,2,2024-10-15,True,1,High,True,3
9999,C10000,53,Male,Mumbai,West,81051.77,519.0,0.00,30,19,...,Investment,Branch,2.0,2,2025-05-16,True,0,Low,True,0

In [86]:
df = df.drop(columns = ["Spend_Per_Transaction"])

KeyError: "['Spend_Per_Transaction'] not found in axis"

In [87]:
# remove columns
df = df.drop(columns = ["Spend_Per_Transaction"],errors = "ignore") #,errors = "ignore"

In [88]:
df

,Customer_ID,Age,Gender,Customer_City,Region,Income,Credit_Score,Account_Balance,Tenure_Months,Num_Transactions,...,Product_Type,Channel,Satisfaction_Score,Complaints,Last_Transaction_Date,Is_Active,Churn,Risk_Band,Marketing_Opt_In,Support_Tickets
0,C00001,23,Other,Hyderabad,South,40823.66,581.0,6084.29,80,12,...,Savings,Web,5.0,1,2025-04-10,True,0,Medium,False,2
1,C00002,62,Male,Delhi,Central,53091.08,805.0,28218.97,196,14,...,Investment,Phone,1.0,0,2024-07-05,True,0,Medium,True,0
2,C00003,55,Male,Delhi,Central,70984.02,421.0,12570.94,42,13,...,Credit Card,Branch,3.0,0,2024-02-09,True,0,Low,False,1
3,C00004,43,Male,Mumbai,South,51176.96,441.0,0.00,37,13,...,Personal Loan,Mobile App,3.0,1,2024-01-08,True,0,High,True,0
4,C00005,43,Unknown,Nagpur,North,58875.94,314.0,20451.36,213,27,...,Savings,Phone,4.0,1,2024-06-18,True,0,Low,True,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,C09996,45,Male,Pune,North,72308.96,NaN,30418.62,161,14,...,Mortgage,Web,5.0,0,2024-09-29,True,0,Medium,True,0
9996,C09997,75,Female,Nagpur,West,51327.02,300.0,29399.98,120,26,...,Savings,Phone,5.0,4,2025-03-11,True,0,High,True,1
9997,C09998,38,Male,Nagpur,South,48316.22,595.0,4564.80,114,11,...,Mortgage,Web,4.0,1,2024-10-09,True,0,Medium,True,1
9998,C09999,50,Unknown,Chennai,West,54334.05,845.0,41852.33,7,19,...,Savings,Mobile App,1.0,2,2024-10-15,True,1,High,True,3
9999,C10000,53,Male,Mumbai,West,81051.77,519.0,0.00,30,19,...,Investment,Branch,2.0,2,2025-05-16,True,0,Low,True,0