In [8]:
import pandas as pd 
import numpy as np

In [9]:
Products = {
    "product":["Laptop","phone","TV"],
    "qty" : [30,np.nan,4],
    "price" : [30000,15000,60000]
}

In [10]:
Products

{'product': ['Laptop', 'phone', 'TV'],
 'qty': [30, nan, 4],
 'price': [30000, 15000, 60000]}

In [11]:
df = pd.DataFrame(Products)

In [12]:
df

  product   qty  price
0  Laptop  30.0  30000
1   phone   NaN  15000
2      TV   4.0  60000

In [28]:
# Find the revenue the company

# first we need to convert the nan to 0 so we perform operation on that
units = df["qty"].to_numpy()
price = df["price"].to_numpy() #here we doesnt applt tonumy to product because we need only numercic value str not convert to num

In [32]:
unit_cl = np.nan_to_num(units,nan=0.0)
price_cl = np.nan_to_num(price,nan=0.0)

In [35]:
rev = unit_cl * price_cl

In [36]:
rev

array([900000.,      0., 240000.])

In [37]:
df["Revenue"] =rev

In [38]:
df

  product   qty  price   Revenue
0  Laptop  30.0  30000  900000.0
1   phone   NaN  15000       0.0
2      TV   4.0  60000  240000.0