### 1: Add 10 to every element

In [1]:
import numpy as np

In [3]:
num = np.array([5,10,15,20])
res= num+10
print(res)

[15 20 25 30]

### 2: Select values greater than 50 
### Question: From [20, 65, 80, 45, 90], select values greater than 50.

In [6]:
arr = np.array([20,65,80,45,90])
filtterarr = [arr > 50]
print(filtterarr)

[array([False,  True,  True, False,  True])]

In [7]:
filtterarr = arr[arr > 50]
print(filtterarr)

[65 80 90]

### Question: Find the mean and maximum of [10, 20, 30, 40, 50].

In [10]:
num = np.array([10,20,30,40,50])
print(f"Maximum value : {np.max(num)} and \nMean value : {np.mean(num)}")

Maximum value : 50 and
Mean value : 30.0

### Question: Replace every value below 40 in [20, 45, 30, 80, 35] with 40.

In [13]:
arr = np.array([20,45,30,80,35])
arr[arr < 40 ]= 40
print(arr)

[40 45 40 80 40]

### Question: Create numbers from 1 through 12, reshape them into 3 rows and 4 columns, and calculate the sum of each row.

In [18]:
arr = np.arange(1,13)
newarr = arr.reshape(3,4)
print(newarr)
sum = newarr.sum(axis = 1)
print(sum)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[10 26 42]

### Question: Products A, B and C have the following units and prices: 
###  Units: [2, 5, 3] 
###  Price: [100, 50, 200] 
### Calculate revenue using Revenue = Units × Price.

In [20]:
dict = {
    "products" : ["A","B","C"],
    "Units" : [2,5,3],
    "Price" : [100,50,200] 
}

In [21]:
print(dict)

{'products': ['A', 'B', 'C'], 'Units': [2, 5, 3], 'Price': [100, 50, 200]}

In [22]:
import pandas as pd

In [27]:
df = pd.DataFrame(dict)

In [24]:
print(df)

  products  Units  Price
0        A      2    100
1        B      5     50
2        C      3    200

In [28]:
df["Revenue"] = df["Units"] * df["Price"]

In [29]:
print(df)

  products  Units  Price  Revenue
0        A      2    100      200
1        B      5     50      250
2        C      3    200      600

In [ ]:

#using numpy
unit = df["Units"].to_numpy()
price = df["Price"].to_numpy()

In [33]:
df["Revenue"] = unit * price

In [34]:
df

  products  Units  Price  Revenue
0        A      2    100      200
1        B      5     50      250
2        C      3    200      600

### Question: Given the following customer data, select customers aged at least 18 with income of at least ₹40,000. 
###  Age: [17, 25, 40, 32] 
###  Income: [20000, 50000, 70000, 30000]

In [43]:
customer = {
    "Age" : [17,25,40,32],
    "Income" : [20000,50000,70000,30000]
}

In [44]:
df = pd.DataFrame(customer)

In [45]:
df["Age"].to_numpy()
df["Income"].to_numpy()

array([20000, 50000, 70000, 30000])

In [47]:
dff = df[(df["Age"] >= 18) & (df["Income"] >= 40000)]

In [48]:
dff

   Age  Income
1   25   50000
2   40   70000

### Question: Given sales [100, NaN, 300, 200], calculate the mean while ignoring the missing value, then replace the  missing value with that mean.

In [69]:
Sales = pd.DataFrame({"sales" : [100, np.nan,300,200]})
sa = sales.mean()
sa

sales    200.0
dtype: float64

In [70]:
m_Sa = np.nanmean(sales["sales"].to_numpy())

In [71]:
Sales["sales"] = Sales["sales"].filllna(m_Sa)
print("Mean sales:",m_Sa)

AttributeError: 'Series' object has no attribute 'filllna'

In [72]:
#Question: Normalize [10, 20, 30] using the formula:

In [76]:
df = pd.DataFrame({"value" : [10,20,30]})
x = df["value"].to_numpy(dtype=float)

In [77]:
mean = np.mean(x)
std = np.std(x)

In [78]:
df["Normalize"] = (x - mean)/std
print("Mean : ", mean)

Mean :  20.0

In [79]:
print("Popilation std ", std)
df

Popilation std  8.16496580927726

   value  Normalize
0     10  -1.224745
1     20   0.000000
2     30   1.224745

### Question: Create a DataFrame with Product, Units and Price. Calculate revenue, categorize each product as "High" when revenue is at least 500 and "Low" otherwise, and calculate total revenue.

In [96]:
df = pd.DataFrame(
    {
        "product":["A","B","C","D"],
        "Units" : [5,2,3,20],
        "Price" : [400,200,600,500]
    }
)

In [97]:
unit = df["Units"].to_numpy()
price = df["Price"].to_numpy()

In [98]:
df["Revenue"] = unit * price
df

  product  Units  Price  Revenue
0       A      5    400     2000
1       B      2    200      400
2       C      3    600     1800
3       D     20    500    10000

In [99]:
df["Category"] = np.where(df["Revenue"]>=500, "High","Low")

In [100]:
total_rev = np.sum(df["Revenue"])

In [101]:

print("Total Revenue:",total_rev)
df

Total Revenue: 14200

  product  Units  Price  Revenue Category
0       A      5    400     2000     High
1       B      2    200      400      Low
2       C      3    600     1800     High
3       D     20    500    10000     High